import BernoulliRegular.FLT37.PrimaryUnits
import Mathlib.NumberTheory.NumberField.CMField

/-!
# Cyclotomic-unit subgroup of `(𝓞 K)ˣ`

For `K = ℚ(ζ_p)` (`p` an odd prime), Sinnott's index formula relates the
"cyclotomic units" subgroup `C ⊆ (𝓞 K)ˣ` (Washington Definition 8.1)
to the class number `h(K)`: `[(𝓞 K)ˣ : C] = h(K)`.

This file defines:
* `cyclotomicUnitsSubgroup` — `C ⊆ (𝓞 K)ˣ`, the subgroup generated by
  the cyclotomic units `(1-ζ^k)/(1-ζ)` (`k` coprime to `p`) and the
  torsion subgroup (= roots of unity in `𝓞 K`).
* `cyclotomicUnitsPlus` — `C⁺ = C ∩ realUnits K`, the real cyclotomic
  units subgroup.

This is **Step (A)** of the Sinnott / Cor 8.19 bridge construction.
The generating elements `cyclotomicUnitUnit p K k` are already defined
in `BernoulliRegular/FLT37/PrimaryUnits.lean`.

## References

* Washington, *Introduction to Cyclotomic Fields*, 2nd ed., §8.1.
* Sinnott, *On the Stickelberger ideal and the circular units of a
  cyclotomic field*, Annals of Math. 108 (1978).
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField

namespace BernoulliRegular

namespace FLT37

namespace Sinnott

variable (p : ℕ) [hp : Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]






end Sinnott

end FLT37

end BernoulliRegular

end
