module

public import BernoulliRegular.TotallyRealSubfield

/-!
# Primary elements of cyclotomic rings of integers (ticket FLT37b2, scaffold)

For a prime `p`, an element `α ∈ 𝒪_K` of the cyclotomic ring is **primary**
when it is congruent to a rational integer modulo `(ζ - 1)^{2p}`. Following
Vandiver, this is the standard hypothesis under which an `ℓ`-th power ideal
generated by `α` descends through complex conjugation.

This file isolates the definition `IsPrimary` and its basic lemmas. The
deeper consequences — primarity forces `[(α)]` to be `σ`-fixed in the class
group, and hence to descend via `classGroupMap_injective` — are treated in
the companion ticket FLT37b3 once the descent skeleton FLT37b1 is plugged in.

## References

* Washington, *Introduction to Cyclotomic Fields*, §6.4 (definition).
* Borevich–Shafarevich, *Number Theory*, §4.9 (use in Vandiver Lemma 1).
* `FltRegular.NumberTheory.Cyclotomic.MoreLemmas`
  (`zeta_sub_one_dvd_Int_iff`, `exists_zeta_sub_one_dvd_sub_Int`).
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace BernoulliRegular

namespace FLT37

section CyclotomicSetup

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

local notation3 "ζ" => IsCyclotomicExtension.zeta p ℚ K

/-- The element `ζ - 1 ∈ 𝒪_K`, where `ζ` is the standard primitive `p`-th
root of unity supplied by `IsCyclotomicExtension`. This is a uniformizer at
the unique prime above `p`. -/
noncomputable def zetaSubOne : 𝓞 K :=
  (zeta_spec p ℚ K).unit' - 1

end CyclotomicSetup

end FLT37

end BernoulliRegular

end
