module

public import BernoulliRegular.TotallyRealSubfield

/-!
# Primary elements of cyclotomic rings of integers (ticket FLT37b2, scaffold)

For a prime `p`, an element `α ∈ 𝒪_K` of the cyclotomic ring is **primary**
when it is congruent to a rational integer modulo `(ζ - 1)^{2p}`. Following
Vandiver, this is the standard hypothesis under which an `ℓ`-th power ideal
generated by `α` descends through complex conjugation.

This file isolates the definition `IsPrimary` and its basic lemmas. The
deeper consequences — primarity forces `[(α)]` to be `σ`-fixed in the class
group, and hence to descend via `classGroupMap_injective` — are treated in
the companion ticket FLT37b3 once the descent skeleton FLT37b1 is plugged in.

## References

* Washington, *Introduction to Cyclotomic Fields*, §6.4 (definition).
* Borevich–Shafarevich, *Number Theory*, §4.9 (use in Vandiver Lemma 1).
* `FltRegular.NumberTheory.Cyclotomic.MoreLemmas`
  (`zeta_sub_one_dvd_Int_iff`, `exists_zeta_sub_one_dvd_sub_Int`).
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace BernoulliRegular

namespace FLT37

section CyclotomicSetup

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

local notation3 "ζ" => IsCyclotomicExtension.zeta p ℚ K

/-- The element `ζ - 1 ∈ 𝒪_K`, where `ζ` is the standard primitive `p`-th
root of unity supplied by `IsCyclotomicExtension`. This is a uniformizer at
the unique prime above `p`. -/
noncomputable def zetaSubOne : 𝓞 K :=
  (zeta_spec p ℚ K).unit' - 1

variable {p K} in
@[simp]
theorem zetaSubOne_def :
    (zetaSubOne p K : 𝓞 K) = (zeta_spec p ℚ K).unit' - 1 :=
  rfl

/-- The image of `zetaSubOne p K` in `K` via the algebra map is `ζ - 1`. -/
theorem algebraMap_zetaSubOne :
    algebraMap (𝓞 K) K (zetaSubOne p K) = ζ - 1 := by
  rw [zetaSubOne_def]
  push_cast
  rfl

/-- **Norm of `ζ - 1` (rational form).** For an odd prime `p` and the cyclotomic
field `K = ℚ(ζ_p)`, the field-level norm of `ζ - 1` is `p`. -/
theorem zetaSubOne_norm_rat (hp_odd : p ≠ 2) :
    Algebra.norm ℚ (algebraMap (𝓞 K) K (zetaSubOne p K)) = (p : ℚ) := by
  rw [algebraMap_zetaSubOne]
  have h_irr := Polynomial.cyclotomic.irreducible_rat hp.1.pos
  have h_norm := (zeta_spec p ℚ K).sub_one_norm_isPrimePow hp.1.isPrimePow h_irr hp_odd
  rw [h_norm, Nat.Prime.minFac_eq hp.1]




/-- `zetaSubOne p K` is a prime element of `𝓞 K`. -/
theorem zetaSubOne_prime : Prime (zetaSubOne p K) :=
  (zeta_spec p ℚ K).zeta_sub_one_prime'

/-- `zetaSubOne p K` is non-zero. -/
theorem zetaSubOne_ne_zero : zetaSubOne p K ≠ 0 :=
  (zetaSubOne_prime p K).ne_zero



/-- **Norm of `ζ^k - 1`.** For an odd prime `p` and `k` coprime to `p`,
the field-level norm of `ζ^k - 1` over `ℚ` is `p`. -/
theorem zeta_pow_sub_one_norm_rat (hp_odd : p ≠ 2) (k : ℕ) (hk : k.Coprime p) :
    Algebra.norm ℚ (ζ ^ k - 1) = (p : ℚ) := by
  have hζk : IsPrimitiveRoot (ζ ^ k) p :=
    (zeta_spec p ℚ K).pow_of_coprime k hk
  have h_irr := Polynomial.cyclotomic.irreducible_rat hp.1.pos
  rw [hζk.sub_one_norm_isPrimePow hp.1.isPrimePow h_irr hp_odd, Nat.Prime.minFac_eq hp.1]

variable {K}

/-- An element `α ∈ 𝒪_K` is **primary** when it is congruent to some rational
integer modulo `(ζ - 1)^{2p}`. -/
def IsPrimary (α : 𝓞 K) : Prop :=
  ∃ a : ℤ, (zetaSubOne p K) ^ (2 * p) ∣ α - (a : 𝓞 K)

/-- An element `α ∈ 𝒪_K` is **semi-primary** when it is congruent to some
rational integer modulo `(ζ - 1)^2`.

This is the congruence strength used in the classical principal-unit-factor
argument: the stronger project convention `IsPrimary`, modulo
`(ζ - 1)^{2p}`, implies this immediately. -/
def IsSemiPrimary (α : 𝓞 K) : Prop :=
  ∃ a : ℤ, (zetaSubOne p K) ^ 2 ∣ α - (a : 𝓞 K)

namespace IsSemiPrimary

variable {p}




/-- One is semi-primary. -/
theorem one : IsSemiPrimary p (K := K) 1 :=
  ⟨1, by simp⟩

/-- The negation of a semi-primary element is semi-primary. -/
theorem neg {α : 𝓞 K} (hα : IsSemiPrimary p α) : IsSemiPrimary p (-α) := by
  obtain ⟨a, ha⟩ := hα
  refine ⟨-a, ?_⟩
  have : (-α) - ((-a : ℤ) : 𝓞 K) = -(α - (a : 𝓞 K)) := by push_cast; ring
  rw [this]
  exact ha.neg_right

/-- `IsSemiPrimary` is preserved by `Neg.neg` in both directions. -/
@[simp]
theorem neg_iff {α : 𝓞 K} : IsSemiPrimary p (-α) ↔ IsSemiPrimary p α :=
  ⟨fun h => by simpa using h.neg, fun h => h.neg⟩


/-- The product of two semi-primary elements is semi-primary. -/
theorem mul {α β : 𝓞 K} (hα : IsSemiPrimary p α) (hβ : IsSemiPrimary p β) :
    IsSemiPrimary p (α * β) := by
  obtain ⟨a, ha⟩ := hα
  obtain ⟨b, hb⟩ := hβ
  refine ⟨a * b, ?_⟩
  have heq : α * β - ((a * b : ℤ) : 𝓞 K) =
      (α - (a : 𝓞 K)) * β + (a : 𝓞 K) * (β - (b : 𝓞 K)) := by
    push_cast; ring
  rw [heq]
  exact dvd_add (ha.mul_right _) (hb.mul_left _)




end IsSemiPrimary

namespace IsPrimary

variable {p}





/-- The negation of a primary element is primary. -/
theorem neg {α : 𝓞 K} (hα : IsPrimary p α) : IsPrimary p (-α) := by
  obtain ⟨a, ha⟩ := hα
  refine ⟨-a, ?_⟩
  have : (-α) - ((-a : ℤ) : 𝓞 K) = -(α - (a : 𝓞 K)) := by push_cast; ring
  rw [this]
  exact ha.neg_right

/-- `IsPrimary` is preserved by `Neg.neg` in both directions. -/
@[simp]
theorem neg_iff {α : 𝓞 K} : IsPrimary p (-α) ↔ IsPrimary p α :=
  ⟨fun h => by simpa using h.neg, fun h => h.neg⟩














end IsPrimary

/-!
## Hyperprimary elements (REF-18c2d-main-a)

A stronger condition needed for the symmetric Kummer–Furtwängler
reciprocity. An element `α ∈ 𝒪_K` is **hyperprimary** when it is
locally a `p`-th power at the prime `λ = 1 - ζ_p`, i.e.
`α ∈ K_λ^{×p}`.

The reviewer-recommended encoding is the literal local-field form
`α ∈ K_λ^{×p}`. As a working substitute (until the local-field
equivalence is formalised), we use the classical **congruence form**:

  `α ≡ β^p (mod λ^{p+1})` for some `β ∈ 𝒪_K`.

Reference: Lemmermeyer, *Reciprocity Laws*, §11; Ireland–Rosen,
Ch. 14.

The exact equivalence between the congruence form and the local
`p`-th-power condition (and the precise exponent) is a separate
ticket; the current definition is the working hypothesis used by
`kummer_furtwaengler_reciprocity_hyperprimary` (REF-18c2d-main-c)
and `singular_hyperprimary_principal_symbol_eq_zero`
(REF-18c2d-main-d).
-/

/-- An element `α ∈ 𝒪_K` is **hyperprimary** when it is congruent to a
`p`-th power modulo `λ^{p+1}`, where `λ = 1 - ζ_p`.

This is the working congruence form of the local `p`-th-power
condition `α ∈ K_λ^{×p}`. The precise local-field equivalence is
deferred to a separate ticket. -/
def IsHyperprimary (α : 𝓞 K) : Prop :=
  ∃ β : 𝓞 K, zetaSubOne p K ^ (p + 1) ∣ α - β ^ p

namespace IsHyperprimary










end IsHyperprimary

end CyclotomicSetup

end FLT37

end BernoulliRegular

end
