module

public import KummerCriterion.CyclotomicUnits.NormalizedSubgroup
import KummerCriterion.CyclotomicUnits.IndexDeterminant
import KummerCriterion.LehmerVandiver.PlusCoprime.Sinnott.DetBridge
import Mathlib.NumberTheory.NumberField.Cyclotomic.PID
public import KummerCriterion.LehmerVandiver.PlusCoprime.Sinnott.LogEmbedding

/-!
# P-primary cyclotomic-unit index formula

This file records the p-primary form of Sinnott's cyclotomic-unit index formula
for the real prime-conductor cyclotomic-unit family.
-/

@[expose] public section

noncomputable section

open NumberField

namespace KummerCriterion

variable {p : ℕ} [Fact p.Prime]
variable {K : Type} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-- The full-rank real cyclotomic-unit subgroup used by the existing Sinnott
regulator/index infrastructure: the family generated by the squared real
cyclotomic units, together with torsion in `K⁺`. -/
def cyclotomicUnitIndexSubgroup (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    Subgroup (𝓞 K⁺)ˣ :=
  Subgroup.closure
      (Set.range (LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplusFinRank p K hp_odd hp_three)) ⊔
    NumberField.Units.torsion K⁺

theorem prime_not_dvd_two_pow (hp_odd : p ≠ 2) (r : ℕ) : ¬ p ∣ 2 ^ r :=
  prime_not_dvd_of_dvd_two_pow (Fact.out : Nat.Prime p) hp_odd dvd_rfl

/-- The harmless `2^r` factor in the squared-family normalization has no
effect on p-primary divisibility for odd `p`. -/
theorem prime_dvd_two_pow_mul_iff_dvd (hp_odd : p ≠ 2) (r n : ℕ) :
    p ∣ 2 ^ r * n ↔ p ∣ n := by
  constructor
  · intro h
    rcases (Fact.out : Nat.Prime p).dvd_mul.mp h with hpow | hn
    · exact (prime_not_dvd_two_pow (p := p) hp_odd r hpow).elim
    · exact hn
  · exact fun hn => dvd_mul_of_dvd_right hn (2 ^ r)

/-- P-primary form of the real cyclotomic-unit index formula, conditional on
the existing explicit Sinnott index formula. -/
theorem cyclotomicUnitIndex_primeConductor_pPrimary_of_sinnottIndexFormula
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (hSinnott : LehmerVandiver.Sinnott.SinnottIndexFormula p K hp_odd hp_three) :
    p ∣ (cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three).index ↔
      p ∣ hPlus K := by
  have hindex := LehmerVandiver.Sinnott.index_eq_twoPow_mul_hPlus_of_sinnottIndexFormula
    p K hp_odd hp_three hSinnott
  change (cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three).index =
      2 ^ ((p - 3) / 2) * hPlus K at hindex
  rw [hindex]
  exact prime_dvd_two_pow_mul_iff_dvd (p := p) hp_odd ((p - 3) / 2) (hPlus K)

/-- P-primary cyclotomic-unit index formula from `KummerDirichletDeterminant`. -/
theorem cyclotomicUnitIndex_primeConductor_pPrimary_of_kummerDirichletDeterminant
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (hdet : LehmerVandiver.Sinnott.KummerDirichletDeterminant p K hp_odd hp_three) :
    p ∣ (cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three).index ↔
      p ∣ hPlus K := by
  have hreg : LehmerVandiver.Sinnott.SinnottRegulatorIdentity p K hp_odd hp_three :=
    (LehmerVandiver.Sinnott.sinnottRegulatorIdentity_iff_kummerDirichletDeterminant
      (p := p) (K := K) hp_odd hp_three).1 hdet
  have hSinnott : LehmerVandiver.Sinnott.SinnottIndexFormula p K hp_odd hp_three :=
    LehmerVandiver.Sinnott.sinnottIndexFormula_of_regulatorIdentity
      p K hp_odd hp_three hreg
  exact cyclotomicUnitIndex_primeConductor_pPrimary_of_sinnottIndexFormula
    (p := p) (K := K) hp_odd hp_three hSinnott

end KummerCriterion

end

/-!
# Normalized cyclotomic-unit index theorem

This file transfers the already proved squared-family prime-conductor index
formula to the TeX normalized subgroup `normalizedCPlus`.
-/

@[expose] public section

noncomputable section

open NumberField

namespace KummerCriterion

variable {p : ℕ} [Fact p.Prime]
variable {K : Type} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

theorem CPlusGenerator_eq_cyclotomicUnitFamilyKplus
    (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    CPlusGenerator (p := p) (K := K) hp_three i =
      LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplus p K hp_three i := by
  apply Units.ext
  simp [CPlusGenerator, realCyclotomicUnit, LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplus]

theorem cyclotomicUnitFamilyKplus_mem_CPlus
    (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplus p K hp_three i ∈
      CPlus (p := p) (K := K) hp_three := by
  rw [← CPlusGenerator_eq_cyclotomicUnitFamilyKplus
    (p := p) (K := K) hp_three i]
  exact CPlusGenerator_mem (p := p) (K := K) hp_three i

theorem range_cyclotomicUnitFamilyKplusFinRank_eq
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    Set.range (LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplusFinRank p K hp_odd hp_three) =
      Set.range (LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplus p K hp_three) := by
  classical
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    unfold LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplusFinRank
    exact ⟨i.cast ((NumberField.IsCMField.units_rank_eq_units_rank (K := K)).trans
      (units_rank_eq_prime_sub_three_div_two (p := p) (K := K))), rfl⟩
  · rintro ⟨i, rfl⟩
    unfold LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplusFinRank
    refine ⟨i.cast (((NumberField.IsCMField.units_rank_eq_units_rank (K := K)).trans
      (units_rank_eq_prime_sub_three_div_two (p := p) (K := K))).symm), ?_⟩
    simp

theorem torsionKplus_le_CPlus (hp_three : 3 ≤ p) :
    NumberField.Units.torsion K⁺ ≤ CPlus (p := p) (K := K) hp_three := by
  intro x hx
  rcases maximalRealSubfield_torsion_eq_one_or_neg_one
      (K := K) ⟨x, hx⟩ with h_one | h_neg
  · have hx_one : x = 1 := by
      simpa using h_one
    rw [hx_one]
    exact Subgroup.one_mem _
  · have hx_neg : x = -1 := by
      simpa using h_neg
    rw [hx_neg]
    exact neg_one_mem_CPlus (p := p) (K := K) hp_three

theorem closure_cyclotomicUnitFamilyKplus_le_CPlus
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    Subgroup.closure
        (Set.range
          (LehmerVandiver.Sinnott.cyclotomicUnitFamilyKplusFinRank p K hp_odd hp_three)) ≤
      CPlus (p := p) (K := K) hp_three := by
  rw [Subgroup.closure_le, range_cyclotomicUnitFamilyKplusFinRank_eq
    (p := p) (K := K) hp_odd hp_three]
  rintro x ⟨i, rfl⟩
  exact cyclotomicUnitFamilyKplus_mem_CPlus (p := p) (K := K) hp_three i

theorem CPlus_le_cyclotomicUnitIndexSubgroup
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    CPlus (p := p) (K := K) hp_three ≤
      cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three := by
  unfold CPlus cyclotomicUnitIndexSubgroup
  rw [Subgroup.closure_le]
  rintro x (hx | hx)
  · rcases hx with rfl
    exact Subgroup.mem_sup_right <| neg_one_mem_torsion
  · rcases hx with ⟨i, rfl⟩
    rw [CPlusGenerator_eq_cyclotomicUnitFamilyKplus (p := p) (K := K) hp_three i]
    exact Subgroup.mem_sup_left <| Subgroup.subset_closure <|
      range_cyclotomicUnitFamilyKplusFinRank_eq (p := p) (K := K) hp_odd hp_three ▸
        Set.mem_range_self i

theorem cyclotomicUnitIndexSubgroup_le_CPlus
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three ≤
      CPlus (p := p) (K := K) hp_three := by
  unfold cyclotomicUnitIndexSubgroup
  exact sup_le
    (closure_cyclotomicUnitFamilyKplus_le_CPlus (p := p) (K := K) hp_odd hp_three)
    (torsionKplus_le_CPlus (p := p) (K := K) hp_three)

theorem cyclotomicUnitIndexSubgroup_eq_CPlus
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three =
      CPlus (p := p) (K := K) hp_three :=
  le_antisymm
    (cyclotomicUnitIndexSubgroup_le_CPlus (p := p) (K := K) hp_odd hp_three)
    (CPlus_le_cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three)

open Classical in
theorem kummerDirichletDeterminant_of_deletedFourier
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) (hp_two : 2 < p) (hp_ge_five : 5 ≤ p) :
    LehmerVandiver.Sinnott.KummerDirichletDeterminant p K hp_odd hp_three := by
  have hdetAB :=
    CyclotomicUnits.detASubBSqEqProdNontrivialQeSq_of_deletedFourier
      (p := p) (K := K) hp_odd hp_three hp_two hp_ge_five
  have hreg :=
    LehmerVandiver.Sinnott.regOfFamilySqEqProdNontrivialQeSq_of_detASubBSqEqProdQeSq
      (p := p) K hp_odd hp_three hp_two hdetAB
  exact LehmerVandiver.Sinnott.KummerDirichletDeterminant_of_regOfFamilySqEqProdNontrivialQeSq
    (p := p) K hp_odd hp_three hp_two hreg

theorem cyclotomicUnitIndex_primeConductor_pPrimary_aux
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) (hp_two : 2 < p) (hp_ge_five : 5 ≤ p) :
    p ∣ (normalizedCPlus (p := p) (K := K) hp_odd hp_three).index ↔ p ∣ hPlus K := by
  have hdet :=
    kummerDirichletDeterminant_of_deletedFourier
      (p := p) (K := K) hp_odd hp_three hp_two hp_ge_five
  have h_square :=
    cyclotomicUnitIndex_primeConductor_pPrimary_of_kummerDirichletDeterminant
      (p := p) (K := K) hp_odd hp_three hdet
  have h_CPlus :
      p ∣ (CPlus (p := p) (K := K) hp_three).index ↔ p ∣ hPlus K := by
    rw [← cyclotomicUnitIndexSubgroup_eq_CPlus (p := p) (K := K) hp_odd hp_three]
    exact h_square
  exact
    (CPlus_index_prime_dvd_iff_normalizedCPlus_index_prime_dvd
      (p := p) (K := K) hp_odd hp_three).symm.trans h_CPlus

theorem hPlus_eq_one_of_eq_three (hp_odd : p ≠ 2) (hp_eq : p = 3) :
    hPlus K = 1 := by
  subst p
  have : IsPrincipalIdealRing (𝓞 K) := IsCyclotomicExtension.Rat.three_pid K
  have h_dvd : hPlus K ∣ h K :=
    hPlus_dvd_h (p := 3) (hp_odd := by norm_num) (K := K)
  have h_one : h K = 1 := by
    have h_class : NumberField.classNumber K = 1 :=
      NumberField.classNumber_eq_one_iff.mpr inferInstance
    simpa [h, NumberField.classNumber] using h_class
  rw [h_one] at h_dvd
  exact Nat.eq_one_of_dvd_one h_dvd

theorem CPlus_eq_top_of_eq_three
    (hp_three : 3 ≤ p) (hp_eq : p = 3) :
    CPlus (p := p) (K := K) hp_three = ⊤ := by
  have h_rank : NumberField.Units.rank K⁺ = 0 := by
    have h_rank_eq :=
      (NumberField.IsCMField.units_rank_eq_units_rank (K := K)).trans
        (units_rank_eq_prime_sub_three_div_two (p := p) (K := K))
    simpa [hp_eq] using h_rank_eq
  apply le_antisymm le_top
  rw [← NumberField.Units.closure_fundSystem_sup_torsion_eq_top (K := K⁺)]
  refine sup_le ?_ (torsionKplus_le_CPlus (p := p) (K := K) hp_three)
  rw [Subgroup.closure_le]
  rintro x ⟨i, rfl⟩
  have hi : (i : ℕ) < 0 := by
    simpa [h_rank] using i.isLt
  omega

theorem normalizedCPlus_eq_top_of_eq_three
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) (hp_eq : p = 3) :
    normalizedCPlus (p := p) (K := K) hp_odd hp_three = ⊤ := by
  apply le_antisymm le_top
  have hle := CPlus_le_normalizedCPlus (p := p) (K := K) hp_odd hp_three
  simpa [CPlus_eq_top_of_eq_three (p := p) (K := K) hp_three hp_eq] using hle

theorem cyclotomicUnitIndex_primeConductor_pPrimary_of_eq_three
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) (hp_eq : p = 3) :
    p ∣ (normalizedCPlus (p := p) (K := K) hp_odd hp_three).index ↔ p ∣ hPlus K := by
  have h_index :
      (normalizedCPlus (p := p) (K := K) hp_odd hp_three).index = 1 := by
    rw [normalizedCPlus_eq_top_of_eq_three (p := p) (K := K) hp_odd hp_three hp_eq]
    exact Subgroup.index_top
  have h_hPlus : hPlus K = 1 :=
    hPlus_eq_one_of_eq_three (p := p) (K := K) hp_odd hp_eq
  rw [h_index, h_hPlus]

theorem cyclotomicUnitIndex_primeConductor_pPrimary_of_five_le (hp_ge_five : 5 ≤ p) :
    p ∣ (normalizedCPlus (p := p) (K := K)
        (by omega : p ≠ 2) (by omega : 3 ≤ p)).index ↔
      p ∣ hPlus K :=
  cyclotomicUnitIndex_primeConductor_pPrimary_aux
    (p := p) (K := K) (by omega) (by omega) (by omega) hp_ge_five

/-- The prime-conductor cyclotomic-unit index theorem for the TeX
normalized subgroup `C⁺ = <-1, ε₂,..., ε_g>`, in odd-primary form. -/
theorem cyclotomicUnitIndex_primeConductor_pPrimary (hp_odd : p ≠ 2) :
    p ∣ (normalizedCPlus (p := p) (K := K) hp_odd
        (by have hp_two := (Fact.out : Nat.Prime p).two_le; omega)).index ↔
      p ∣ hPlus K := by
  by_cases hp_eq : p = 3
  · exact cyclotomicUnitIndex_primeConductor_pPrimary_of_eq_three
      (p := p) (K := K) hp_odd
      (by have hp_two := (Fact.out : Nat.Prime p).two_le; omega) hp_eq
  · have hp_ge_five : 5 ≤ p := by
      obtain ⟨k, hk⟩ := (Fact.out : Nat.Prime p).odd_of_ne_two hp_odd
      have hp_two := (Fact.out : Nat.Prime p).two_le
      omega
    exact cyclotomicUnitIndex_primeConductor_pPrimary_of_five_le
      (p := p) (K := K) hp_ge_five

end KummerCriterion

end
