module

import Mathlib.Analysis.SpecialFunctions.Bernstein
public import KummerCriterion.LehmerVandiver.PrimaryUnits.Part3

/-!
# Real cyclotomic units

This file gives the standard real cyclotomic units in `K⁺` a route-level name.
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField

namespace KummerCriterion

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-- Indices `2 ≤ a ≤ (p - 1) / 2` are automatically coprime to the prime
conductor `p`. -/
theorem realCyclotomicUnit_index_coprime {a : ℕ}
    (ha_two : 2 ≤ a) (ha_le : a ≤ (p - 1) / 2) : a.Coprime p := by
  have hp_prime : Nat.Prime p := Fact.out
  have ha_pos : 0 < a := by omega
  have ha_lt : a < p := by
    have hhalf : (p - 1) / 2 < p := by omega
    omega
  have hnot : ¬ p ∣ a := fun hpa => by
    exact (not_le_of_gt ha_lt) (Nat.le_of_dvd ha_pos hpa)
  exact (hp_prime.coprime_iff_not_dvd.mpr hnot).symm

/-- The real cyclotomic unit in `𝓞 K⁺` attached to `2 ≤ a ≤ (p - 1) / 2`. -/
noncomputable def realCyclotomicUnit (a : ℕ)
    (ha_two : 2 ≤ a) (ha_le : a ≤ (p - 1) / 2) : (𝓞 K⁺)ˣ :=
  LehmerVandiver.realCyclotomicUnitPlusUnit p K a
    (realCyclotomicUnit_index_coprime (p := p) ha_two ha_le)
    (Fact.out : Nat.Prime p).two_le

@[simp]
theorem realCyclotomicUnit_val (a : ℕ)
    (ha_two : 2 ≤ a) (ha_le : a ≤ (p - 1) / 2) :
    (realCyclotomicUnit (p := p) (K := K) a ha_two ha_le : 𝓞 K⁺) =
      LehmerVandiver.realCyclotomicUnitPlus p K a := by
  unfold realCyclotomicUnit
  rw [LehmerVandiver.realCyclotomicUnitPlusUnit_val]

/-- The image of the real cyclotomic unit in `𝓞 K` is the σ-fixed product
`cyclotomicUnit a * σ(cyclotomicUnit a)`. -/
theorem algebraMap_realCyclotomicUnit (a : ℕ)
    (ha_two : 2 ≤ a) (ha_le : a ≤ (p - 1) / 2) :
    algebraMap (𝓞 K⁺) (𝓞 K)
        (realCyclotomicUnit (p := p) (K := K) a ha_two ha_le : 𝓞 K⁺) =
      LehmerVandiver.realCyclotomicUnit p K a := by
  rw [realCyclotomicUnit_val, LehmerVandiver.algebraMap_realCyclotomicUnitPlus]

end KummerCriterion

end

/-!
# The real cyclotomic-unit subgroup

This file defines the prime-conductor real cyclotomic-unit subgroup `CPlus`
inside `(𝓞 K⁺)ˣ`, generated by `-1` and the standard real cyclotomic units
with indices `2,..., (p - 1) / 2`.
-/

@[expose] public section

noncomputable section

open NumberField

namespace KummerCriterion

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-- The `i`th standard real cyclotomic-unit index is `i + 2`. -/
abbrev CPlusGeneratorIndex (_hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) : ℕ :=
  (i : ℕ) + 2

omit [Fact p.Prime] in
theorem CPlusGeneratorIndex_two_le (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    2 ≤ CPlusGeneratorIndex (p := p) hp_three i := by
  simp [CPlusGeneratorIndex]

theorem CPlusGeneratorIndex_le_half (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    CPlusGeneratorIndex (p := p) hp_three i ≤ (p - 1) / 2 := by
  have hi : (i : ℕ) < (p - 3) / 2 := i.isLt
  have hp_odd_mod : p % 2 = 1 :=
    Nat.odd_iff.mp ((Fact.out : Nat.Prime p).odd_of_ne_two (by omega))
  have hhalf : (p - 1) / 2 = (p - 3) / 2 + 1 := by
    omega
  dsimp [CPlusGeneratorIndex]
  rw [hhalf]
  omega

/-- The finite generator family `a = 2,..., (p - 1) / 2`, indexed by
`Fin ((p - 3) / 2)`. -/
noncomputable def CPlusGenerator (hp_three : 3 ≤ p)
    (i : Fin ((p - 3) / 2)) : (𝓞 K⁺)ˣ :=
  realCyclotomicUnit (p := p) (K := K) (CPlusGeneratorIndex (p := p) hp_three i)
    (CPlusGeneratorIndex_two_le (p := p) hp_three i)
    (CPlusGeneratorIndex_le_half (p := p) hp_three i)

/-- The real cyclotomic-unit subgroup `C⁺`, generated by `-1` and the
standard real cyclotomic units. -/
def CPlus (hp_three : 3 ≤ p) : Subgroup (𝓞 K⁺)ˣ :=
  Subgroup.closure
    ({(-1 : (𝓞 K⁺)ˣ)} ∪ Set.range (CPlusGenerator (p := p) (K := K) hp_three))

theorem neg_one_mem_CPlus (hp_three : 3 ≤ p) :
    (-1 : (𝓞 K⁺)ˣ) ∈ CPlus (p := p) (K := K) hp_three :=
  Subgroup.subset_closure (by left; rfl)

theorem CPlusGenerator_mem (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    CPlusGenerator (p := p) (K := K) hp_three i ∈ CPlus (p := p) (K := K) hp_three :=
  Subgroup.subset_closure (by right; exact ⟨i, rfl⟩)

/-- The full real-unit subgroup on the plus side. -/
def EPlus : Subgroup (𝓞 K⁺)ˣ :=
  ⊤

/-- Exact image of the `p`th-power map on a subgroup. This is not a closure. -/
def pPowerSubgroup {G : Type*} [CommGroup G] (H : Subgroup G) (p : ℕ) : Subgroup G where
  carrier := {x | ∃ y : G, y ∈ H ∧ y ^ p = x}
  one_mem' := by
    refine ⟨1, H.one_mem, by simp⟩
  mul_mem' := by
    rintro x y ⟨a, haH, rfl⟩ ⟨b, hbH, rfl⟩
    refine ⟨a * b, H.mul_mem haH hbH, ?_⟩
    simp [mul_pow]
  inv_mem' := by
    rintro x ⟨a, haH, rfl⟩
    refine ⟨a⁻¹, H.inv_mem haH, ?_⟩
    simp [inv_pow]

/-- `H` is `p`-saturated in `E` if an element of `H` that is a `p`th power in
`E` is already a `p`th power in `H`. -/
def pSaturated {G : Type*} [CommGroup G] (H E : Subgroup G) (p : ℕ) : Prop :=
  H ≤ E ∧ H ⊓ pPowerSubgroup E p ≤ pPowerSubgroup H p

theorem pSaturated.mem_pPowerSubgroup_of_mem {G : Type*} [CommGroup G]
    {H E : Subgroup G} {p : ℕ} (h : pSaturated H E p) {x : G}
    (hxH : x ∈ H) (hxEpow : x ∈ pPowerSubgroup E p) :
    x ∈ pPowerSubgroup H p :=
  h.2 ⟨hxH, hxEpow⟩

theorem CPlus_le_EPlus (hp_three : 3 ≤ p) :
    CPlus (p := p) (K := K) hp_three ≤ EPlus (K := K) := by
  simp [EPlus]

/-- Integer-exponent product of the sign and the finite `CPlus` generators. -/
noncomputable def CPlusExponentProduct (hp_three : 3 ≤ p) (s : ℤ)
    (e : Fin ((p - 3) / 2) → ℤ) : (𝓞 K⁺)ˣ :=
  (-1 : (𝓞 K⁺)ˣ) ^ s *
    ∏ a : Fin ((p - 3) / 2),
      CPlusGenerator (p := p) (K := K) hp_three a ^ e a

theorem CPlusExponentProduct_mul (hp_three : 3 ≤ p) (s t : ℤ)
    (e f : Fin ((p - 3) / 2) → ℤ) :
    CPlusExponentProduct (p := p) (K := K) hp_three s e *
        CPlusExponentProduct (p := p) (K := K) hp_three t f =
      CPlusExponentProduct (p := p) (K := K) hp_three (s + t) (e + f) := by
  classical
  simp [CPlusExponentProduct, zpow_add, Finset.prod_mul_distrib, mul_assoc, mul_left_comm]

theorem CPlusExponentProduct_inv (hp_three : 3 ≤ p) (s : ℤ)
    (e : Fin ((p - 3) / 2) → ℤ) :
    (CPlusExponentProduct (p := p) (K := K) hp_three s e)⁻¹ =
      CPlusExponentProduct (p := p) (K := K) hp_three (-s) (-e) := by
  classical
  simp [CPlusExponentProduct, Finset.prod_inv_distrib, mul_comm]

theorem CPlusExponentProduct_single (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    CPlusExponentProduct (p := p) (K := K) hp_three 0
        (fun j => if j = i then 1 else 0) =
      CPlusGenerator (p := p) (K := K) hp_three i := by
  classical
  unfold CPlusExponentProduct
  simp only [zpow_zero, one_mul]
  rw [Finset.prod_eq_single i]
  · simp
  · intro j _ hj
    simp [hj]
  · intro hi
    exact False.elim (hi (Finset.mem_univ i))

theorem CPlusExponentProduct_mem_CPlus (hp_three : 3 ≤ p) (s : ℤ)
    (e : Fin ((p - 3) / 2) → ℤ) :
    CPlusExponentProduct (p := p) (K := K) hp_three s e ∈
      CPlus (p := p) (K := K) hp_three := by
  classical
  unfold CPlusExponentProduct
  exact (CPlus (p := p) (K := K) hp_three).mul_mem
    ((CPlus (p := p) (K := K) hp_three).zpow_mem
      (neg_one_mem_CPlus (p := p) (K := K) hp_three) s)
    ((CPlus (p := p) (K := K) hp_three).prod_mem fun a _ =>
      (CPlus (p := p) (K := K) hp_three).zpow_mem
        (CPlusGenerator_mem (p := p) (K := K) hp_three a) (e a))

/-- Every element of `CPlus` has an integer-exponent expression in the sign and
the finite cyclotomic-unit generators. -/
theorem exists_CPlusExponentProduct_of_mem_CPlus (hp_three : 3 ≤ p)
    {x : (𝓞 K⁺)ˣ} (hx : x ∈ CPlus (p := p) (K := K) hp_three) :
    ∃ (s : ℤ) (e : Fin ((p - 3) / 2) → ℤ),
      CPlusExponentProduct (p := p) (K := K) hp_three s e = x := by
  classical
  unfold CPlus at hx
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with hx | hx
      · rcases hx with rfl
        refine ⟨1, 0, ?_⟩
        simp [CPlusExponentProduct]
      · rcases hx with ⟨i, rfl⟩
        refine ⟨0, (fun j => if j = i then 1 else 0), ?_⟩
        exact CPlusExponentProduct_single (p := p) (K := K) hp_three i
  | one =>
      refine ⟨0, 0, ?_⟩
      simp [CPlusExponentProduct]
  | mul x y _ _ hx hy =>
      rcases hx with ⟨s, e, hx⟩
      rcases hy with ⟨t, f, hy⟩
      refine ⟨s + t, e + f, ?_⟩
      rw [← hx, ← hy, CPlusExponentProduct_mul]
  | inv x _ hx =>
      rcases hx with ⟨s, e, hx⟩
      refine ⟨-s, -e, ?_⟩
      rw [← hx, ← CPlusExponentProduct_inv]

theorem zpow_pow_eq_self_of_sq_eq_one_of_odd {G : Type*} [CommGroup G] {x : G}
    (hx_sq : x ^ 2 = 1) {n : ℕ} (hn_odd : n % 2 = 1) (s : ℤ) :
    (x ^ s) ^ n = x ^ s := by
  have hn_split : n = 2 * (n / 2) + 1 := by omega
  have hxs_sq : (x ^ s) ^ 2 = 1 := by
    calc
      (x ^ s) ^ 2 = (x ^ s) ^ (2 : ℤ) :=
        (zpow_natCast (x ^ s) 2).symm
      _ = x ^ (s * (2 : ℤ)) := by rw [zpow_mul]
      _ = x ^ ((2 : ℤ) * s) := by rw [mul_comm]
      _ = (x ^ (2 : ℤ)) ^ s := by rw [zpow_mul]
      _ = (x ^ 2) ^ s :=
        congrArg (fun y : G => y ^ s) (zpow_natCast x 2)
      _ = 1 := by rw [hx_sq, one_zpow]
  calc
    (x ^ s) ^ n = (x ^ s) ^ (2 * (n / 2) + 1) :=
      congrArg (fun m : ℕ => (x ^ s) ^ m) hn_split
    _ = (x ^ s) ^ (2 * (n / 2)) * x ^ s := by rw [pow_add, pow_one]
    _ = ((x ^ s) ^ 2) ^ (n / 2) * x ^ s := by rw [pow_mul]
    _ = x ^ s := by rw [hxs_sq]; simp

omit [NumberField K] [IsCyclotomicExtension {p} ℚ K] [IsCMField K] in
theorem neg_one_zpow_pow_eq_self (hp_odd : p ≠ 2) (s : ℤ) :
    ((-1 : (𝓞 K⁺)ˣ) ^ s) ^ p = (-1 : (𝓞 K⁺)ˣ) ^ s := by
  have hp_mod : p % 2 = 1 :=
    Nat.odd_iff.mp ((Fact.out : Nat.Prime p).odd_of_ne_two hp_odd)
  have hneg_sq : ((-1 : (𝓞 K⁺)ˣ) ^ 2) = 1 := by
    ext
    simp
  exact zpow_pow_eq_self_of_sq_eq_one_of_odd hneg_sq hp_mod s

theorem CPlusExponentProduct_pow_of_exponents_eq_mul (hp_odd : p ≠ 2)
    (hp_three : 3 ≤ p) (s : ℤ) (e k : Fin ((p - 3) / 2) → ℤ)
    (hk : ∀ a, e a = (p : ℤ) * k a) :
    CPlusExponentProduct (p := p) (K := K) hp_three s k ^ p =
      CPlusExponentProduct (p := p) (K := K) hp_three s e := by
  classical
  unfold CPlusExponentProduct
  rw [mul_pow, neg_one_zpow_pow_eq_self (p := p) (K := K) hp_odd s,
    ← Finset.prod_pow]
  congr 1
  refine Finset.prod_congr rfl ?_
  intro a _
  calc
    (CPlusGenerator (p := p) (K := K) hp_three a ^ k a) ^ p =
        CPlusGenerator (p := p) (K := K) hp_three a ^ (k a * (p : ℤ)) := by
          rw [← zpow_natCast, zpow_mul]
    _ = CPlusGenerator (p := p) (K := K) hp_three a ^ ((p : ℤ) * k a) := by
          rw [mul_comm]
    _ = CPlusGenerator (p := p) (K := K) hp_three a ^ e a := by
          rw [hk a]

/-- Concrete group-theoretic saturation criterion for `CPlus`. -/
theorem CPlus_pSaturated_of_generator_exponents_modP_zero (hp_odd : p ≠ 2)
    (hp_three : 3 ≤ p)
    (h : ∀ (s : ℤ) (e : Fin ((p - 3) / 2) → ℤ),
      CPlusExponentProduct (p := p) (K := K) hp_three s e ∈
          pPowerSubgroup (EPlus (K := K)) p →
        ∀ a, (e a : ZMod p) = 0) :
    pSaturated (CPlus (p := p) (K := K) hp_three) (EPlus (K := K)) p := by
  classical
  refine ⟨CPlus_le_EPlus (p := p) (K := K) hp_three, ?_⟩
  intro x hx
  rcases hx with ⟨hxC, hxEpow⟩
  rcases exists_CPlusExponentProduct_of_mem_CPlus
      (p := p) (K := K) hp_three hxC with
    ⟨s, e, hxe⟩
  have hzero : ∀ a, (e a : ZMod p) = 0 := by
    refine h s e ?_
    simpa [hxe] using hxEpow
  have hdiv : ∀ a, (p : ℤ) ∣ e a := fun a =>
    (CharP.intCast_eq_zero_iff (ZMod p) p (e a)).mp (hzero a)
  choose k hk using hdiv
  refine ⟨CPlusExponentProduct (p := p) (K := K) hp_three s k,
    CPlusExponentProduct_mem_CPlus (p := p) (K := K) hp_three s k, ?_⟩
  calc
    CPlusExponentProduct (p := p) (K := K) hp_three s k ^ p =
        CPlusExponentProduct (p := p) (K := K) hp_three s e :=
          CPlusExponentProduct_pow_of_exponents_eq_mul
            (p := p) (K := K) hp_odd hp_three s e k hk
    _ = x := hxe

end KummerCriterion

end
