module

public import KummerCriterion.CyclotomicUnits.Basic

/-!
# The real cyclotomic-unit subgroup

This file defines the prime-conductor real cyclotomic-unit subgroup `CPlus`
inside `(𝓞 K⁺)ˣ`, generated by `-1` and the standard real cyclotomic units
with indices `2, ..., (p - 1) / 2`.
-/

@[expose] public section

noncomputable section

open NumberField

namespace KummerCriterion

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-- The `i`th standard real cyclotomic-unit index is `i + 2`. -/
abbrev CPlusGeneratorIndex (_hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) : ℕ :=
  (i : ℕ) + 2

omit [Fact p.Prime] in
theorem CPlusGeneratorIndex_two_le (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    2 ≤ CPlusGeneratorIndex (p := p) hp_three i := by
  simp [CPlusGeneratorIndex]

theorem CPlusGeneratorIndex_le_half (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    CPlusGeneratorIndex (p := p) hp_three i ≤ (p - 1) / 2 := by
  have hi : (i : ℕ) < (p - 3) / 2 := i.isLt
  have hp_odd_mod : p % 2 = 1 :=
    Nat.odd_iff.mp ((Fact.out : Nat.Prime p).odd_of_ne_two (by omega))
  have hhalf : (p - 1) / 2 = (p - 3) / 2 + 1 := by
    omega
  dsimp [CPlusGeneratorIndex]
  rw [hhalf]
  omega

/-- The finite generator family `a = 2, ..., (p - 1) / 2`, indexed by
`Fin ((p - 3) / 2)`. -/
noncomputable def CPlusGenerator (hp_three : 3 ≤ p)
    (i : Fin ((p - 3) / 2)) : (𝓞 K⁺)ˣ :=
  realCyclotomicUnit (p := p) (K := K) (CPlusGeneratorIndex (p := p) hp_three i)
    (CPlusGeneratorIndex_two_le (p := p) hp_three i)
    (CPlusGeneratorIndex_le_half (p := p) hp_three i)

/-- The real cyclotomic-unit subgroup `C⁺`, generated by `-1` and the
standard real cyclotomic units. -/
def CPlus (hp_three : 3 ≤ p) : Subgroup (𝓞 K⁺)ˣ :=
  Subgroup.closure
    ({(-1 : (𝓞 K⁺)ˣ)} ∪ Set.range (CPlusGenerator (p := p) (K := K) hp_three))

theorem neg_one_mem_CPlus (hp_three : 3 ≤ p) :
    (-1 : (𝓞 K⁺)ˣ) ∈ CPlus (p := p) (K := K) hp_three :=
  Subgroup.subset_closure (by left; rfl)

theorem CPlusGenerator_mem (hp_three : 3 ≤ p) (i : Fin ((p - 3) / 2)) :
    CPlusGenerator (p := p) (K := K) hp_three i ∈ CPlus (p := p) (K := K) hp_three :=
  Subgroup.subset_closure (by right; exact ⟨i, rfl⟩)

/-- An odd prime does not divide the sign factor `2`. -/
theorem prime_not_dvd_sign_factor (hp_odd : p ≠ 2) : ¬ p ∣ (2 : ℕ) := by
  intro hp_dvd_two
  have hp_le_two : p ≤ 2 := Nat.le_of_dvd (by norm_num) hp_dvd_two
  exact hp_odd (le_antisymm hp_le_two (Fact.out : Nat.Prime p).two_le)

end KummerCriterion

end
