module

public import KummerCriterion.TotallyRealSubfield.ZetaPrime

/-!
# Local cyclotomic setup at `lambda`

This file packages the basic local objects used in the reflection argument by
localizing `𝓞 K` at the distinguished prime `zetaPrime p K` generated by
`ζ_p - 1`.

At this stage we only need the local ring, its maximal ideal, the unit group,
and the principal-unit filtration. Those are the inputs for the later
local calculations.
-/

@[expose] public section

noncomputable section

open scoped NumberField

namespace KummerCriterion

namespace Ideal

section OneUnits

variable {R : Type*} [CommRing R]

/-- The subgroup of units congruent to `1` modulo `I`. -/
def oneUnitsSubgroup (I : Ideal R) : Subgroup Rˣ where
  carrier := {u | (u : R) - 1 ∈ I}
  one_mem' := by
    simp
  mul_mem' {u v} hu hv := by
    simpa using I.mul_sub_mul_mem hu hv
  inv_mem' {u} hu := by
    have hmul : ((u : R) * (((u⁻¹ : Rˣ) : R) - 1)) ∈ I := by
      simpa [sub_eq_add_neg, mul_add, add_comm, add_left_comm, add_assoc] using I.neg_mem hu
    exact (Ideal.unit_mul_mem_iff_mem (I := I) (x := ((u⁻¹ : Rˣ) : R) - 1)
      (y := (u : R)) u.isUnit).mp hmul

@[simp]
theorem mem_oneUnitsSubgroup {R : Type*} [CommRing R] {I : Ideal R} {u : Rˣ} :
    u ∈ Ideal.oneUnitsSubgroup I ↔ (u : R) - 1 ∈ I :=
  Iff.rfl

end OneUnits

end Ideal

namespace Reflection
namespace Local

section CyclotomicSetup

variable (p : ℕ) [Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The distinguished prime `lambda = (ζ_p - 1)` above `p` in `𝓞 K`. -/
abbrev cyclotomicLambda : Ideal (𝓞 K) := zetaPrime p K

end CyclotomicSetup

end Local
end Reflection

end KummerCriterion
