module

public import Mathlib.RingTheory.AdicCompletion.Algebra
public import KummerCriterion.UnitQuotient.DeltaAction
public import Mathlib.Algebra.Lie.OfAssociative
public import KummerCriterion.TotallyRealSubfield.ZetaPrime

/-!
# Local cyclotomic setup at `lambda`

This file packages the basic local objects used in the reflection argument by
localizing `𝓞 K` at the distinguished prime `zetaPrime p K` generated by
`ζ_p - 1`.

At this stage we only need the local ring, its maximal ideal, the unit group,
and the principal-unit filtration. Those are the inputs for the later
local calculations.
-/

@[expose] public section

noncomputable section

open scoped NumberField

namespace KummerCriterion

namespace Ideal

section OneUnits

variable {R : Type*} [CommRing R]

/-- The subgroup of units congruent to `1` modulo `I`. -/
def oneUnitsSubgroup (I : Ideal R) : Subgroup Rˣ where
  carrier := {u | (u : R) - 1 ∈ I}
  one_mem' := by
    simp
  mul_mem' {u v} hu hv := by
    simpa using I.mul_sub_mul_mem hu hv
  inv_mem' {u} hu := by
    have hmul : ((u : R) * (((u⁻¹ : Rˣ) : R) - 1)) ∈ I := by
      simpa [sub_eq_add_neg, mul_add, add_comm, add_left_comm, add_assoc] using I.neg_mem hu
    exact (Ideal.unit_mul_mem_iff_mem (I := I) (x := ((u⁻¹ : Rˣ) : R) - 1)
      (y := (u : R)) u.isUnit).mp hmul

@[simp]
theorem mem_oneUnitsSubgroup {R : Type*} [CommRing R] {I : Ideal R} {u : Rˣ} :
    u ∈ Ideal.oneUnitsSubgroup I ↔ (u : R) - 1 ∈ I :=
  Iff.rfl

end OneUnits

end Ideal

namespace Reflection
namespace Local

section CyclotomicSetup

variable (p : ℕ) [Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The distinguished prime `lambda = (ζ_p - 1)` above `p` in `𝓞 K`. -/
abbrev cyclotomicLambda : Ideal (𝓞 K) := zetaPrime p K

end CyclotomicSetup

end Local
end Reflection

end KummerCriterion

/-!
# Cyclotomic action on lambda-local and completed units

This file starts. It proves that the cyclotomic
`Delta = (ZMod p)^*` automorphisms preserve the distinguished prime
`lambda = (zeta_p - 1)`, hence act on the localization at `lambda` and preserve
the local principal-unit filtration. It also lifts those automorphisms through
the lambda-adic completion.
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField

namespace KummerCriterion
namespace Reflection
namespace Local

section CompletionLift

variable {R : Type*} [CommRing R] (I : Ideal R)

theorem evalₐ_factor_pow_le {m n : ℕ} (hmn : m ≤ n) (x : AdicCompletion I R) :
    Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn) (AdicCompletion.evalₐ I n x) =
      AdicCompletion.evalₐ I m x := by
  change
    Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn)
        ((Ideal.quotientEquivAlgOfEq R (by ext y; simp))
          (AdicCompletion.eval I R n x)) =
      (Ideal.quotientEquivAlgOfEq R (by ext y; simp))
        (AdicCompletion.eval I R m x)
  have htrans :
      AdicCompletion.transitionMap I R hmn ((AdicCompletion.eval I R n) x) =
        ((AdicCompletion.eval I R m) x) :=
    AdicCompletion.transitionMap_comp_eval_apply (I := I) (M := R) hmn x
  rw [← htrans]
  induction ((AdicCompletion.eval I R n) x) using Quotient.inductionOn' with
  | h r =>
    rfl

theorem ideal_pow_map_ringEquiv_eq_of_map_eq
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I) (n : ℕ) :
    (I ^ n).map (e : R →+* R) = I ^ n := by
  rw [Ideal.map_pow, he]

theorem ideal_pow_le_comap_ringEquiv_of_map_eq
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I) (n : ℕ) :
    I ^ n ≤ (I ^ n).comap (e : R →+* R) := by
  rw [← Ideal.map_le_iff_le_comap]
  exact (ideal_pow_map_ringEquiv_eq_of_map_eq (I := I) e he n).le

theorem ideal_map_ringEquiv_symm_eq_of_map_eq
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I) :
    I.map (e.symm : R →+* R) = I := by
  have h := congrArg (fun J : Ideal R => J.map (e.symm : R →+* R)) he
  simpa using h.symm

noncomputable def adicCompletionRingHomOfIdealMapEqFamily
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I) (n : ℕ) :
    AdicCompletion I R →+* R ⧸ I ^ n :=
  (Ideal.quotientMap (I ^ n) (e : R →+* R)
    (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e he n)).comp
    (AdicCompletion.evalₐ I n).toRingHom

theorem adicCompletionRingHomOfIdealMapEqFamily_compatible
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I)
    {m n : ℕ} (hmn : m ≤ n) :
    (Ideal.Quotient.factorPow I hmn).comp
        (adicCompletionRingHomOfIdealMapEqFamily (I := I) e he n) =
      adicCompletionRingHomOfIdealMapEqFamily (I := I) e he m := by
  ext x
  simp only [RingHom.coe_comp, Function.comp_apply]
  change Ideal.Quotient.factor (Ideal.pow_le_pow_right hmn)
        (Ideal.quotientMap (I ^ n) (e : R →+* R)
          (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e he n)
          (AdicCompletion.evalₐ I n x)) =
      Ideal.quotientMap (I ^ m) (e : R →+* R)
        (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e he m)
        (AdicCompletion.evalₐ I m x)
  rw [← evalₐ_factor_pow_le (I := I) hmn x]
  induction AdicCompletion.evalₐ I n x using Quotient.inductionOn' with
  | h r =>
    rfl

/-- A ring automorphism preserving `I` lifts to an endomorphism of the
`I`-adic completion. -/
noncomputable def adicCompletionRingHomOfIdealMapEq
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I) :
    AdicCompletion I R →+* AdicCompletion I R :=
  AdicCompletion.liftRingHom I
    (adicCompletionRingHomOfIdealMapEqFamily (I := I) e he)
    (fun hmn => adicCompletionRingHomOfIdealMapEqFamily_compatible (I := I) e he hmn)

@[simp]
theorem evalₐ_adicCompletionRingHomOfIdealMapEq
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I)
    (n : ℕ) (x : AdicCompletion I R) :
    AdicCompletion.evalₐ I n (adicCompletionRingHomOfIdealMapEq (I := I) e he x) =
      Ideal.quotientMap (I ^ n) (e : R →+* R)
        (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e he n)
        (AdicCompletion.evalₐ I n x) :=
  AdicCompletion.evalₐ_liftRingHom I
    (adicCompletionRingHomOfIdealMapEqFamily (I := I) e he)
    (fun hmn => adicCompletionRingHomOfIdealMapEqFamily_compatible (I := I) e he hmn)
    n x

theorem quotientMap_ringEquiv_symm_apply_quotientMap_ringEquiv
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I)
    (n : ℕ) (x : R ⧸ I ^ n) :
    Ideal.quotientMap (I ^ n) (e.symm : R →+* R)
        (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e.symm
          (ideal_map_ringEquiv_symm_eq_of_map_eq (I := I) e he) n)
        (Ideal.quotientMap (I ^ n) (e : R →+* R)
          (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e he n) x) =
      x := by
  induction x using Quotient.inductionOn' with
  | h r =>
    change Ideal.Quotient.mk (I ^ n) (e.symm (e r)) =
      Ideal.Quotient.mk (I ^ n) r
    rw [RingEquiv.symm_apply_apply]

theorem quotientMap_ringEquiv_apply_quotientMap_ringEquiv_symm
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I)
    (n : ℕ) (x : R ⧸ I ^ n) :
    Ideal.quotientMap (I ^ n) (e : R →+* R)
        (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e he n)
        (Ideal.quotientMap (I ^ n) (e.symm : R →+* R)
          (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e.symm
            (ideal_map_ringEquiv_symm_eq_of_map_eq (I := I) e he) n) x) =
      x := by
  induction x using Quotient.inductionOn' with
  | h r =>
    change Ideal.Quotient.mk (I ^ n) (e (e.symm r)) =
      Ideal.Quotient.mk (I ^ n) r
    rw [RingEquiv.apply_symm_apply]

/-- A ring automorphism preserving `I` lifts to an automorphism of the
`I`-adic completion. -/
noncomputable def adicCompletionRingEquivOfIdealMapEq
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I) :
    AdicCompletion I R ≃+* AdicCompletion I R where
  __ := adicCompletionRingHomOfIdealMapEq (I := I) e he
  invFun :=
    adicCompletionRingHomOfIdealMapEq (I := I) e.symm
      (ideal_map_ringEquiv_symm_eq_of_map_eq (I := I) e he)
  left_inv x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ I n
        (adicCompletionRingHomOfIdealMapEq (I := I) e.symm
          (ideal_map_ringEquiv_symm_eq_of_map_eq (I := I) e he)
          (adicCompletionRingHomOfIdealMapEq (I := I) e he x)) =
      AdicCompletion.evalₐ I n x
    rw [evalₐ_adicCompletionRingHomOfIdealMapEq,
      evalₐ_adicCompletionRingHomOfIdealMapEq,
      quotientMap_ringEquiv_symm_apply_quotientMap_ringEquiv (I := I) e he n]
  right_inv x := by
    apply AdicCompletion.ext_evalₐ
    intro n
    change AdicCompletion.evalₐ I n
        (adicCompletionRingHomOfIdealMapEq (I := I) e he
          (adicCompletionRingHomOfIdealMapEq (I := I) e.symm
            (ideal_map_ringEquiv_symm_eq_of_map_eq (I := I) e he) x)) =
      AdicCompletion.evalₐ I n x
    rw [evalₐ_adicCompletionRingHomOfIdealMapEq,
      evalₐ_adicCompletionRingHomOfIdealMapEq,
      quotientMap_ringEquiv_apply_quotientMap_ringEquiv_symm (I := I) e he n]

@[simp]
theorem evalₐ_adicCompletionRingEquivOfIdealMapEq
    (e : R ≃+* R) (he : I.map (e : R →+* R) = I)
    (n : ℕ) (x : AdicCompletion I R) :
    AdicCompletion.evalₐ I n (adicCompletionRingEquivOfIdealMapEq (I := I) e he x) =
      Ideal.quotientMap (I ^ n) (e : R →+* R)
        (ideal_pow_le_comap_ringEquiv_of_map_eq (I := I) e he n)
        (AdicCompletion.evalₐ I n x) :=
  evalₐ_adicCompletionRingHomOfIdealMapEq (I := I) e he n x

end CompletionLift

section CyclotomicSetup

variable (p : ℕ) [Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The cyclotomic automorphism sends `zeta_p - 1` into the distinguished
prime `(zeta_p - 1)`. -/
theorem cyclotomicRingOfIntegersEquiv_zeta_sub_one_mem_lambda
    (a : CyclotomicUnitDelta p) :
    cyclotomicRingOfIntegersEquiv (p := p) K a
        ((zeta_spec p ℚ K).toInteger - 1) ∈ cyclotomicLambda p K := by
  have hdiv :
      ((zeta_spec p ℚ K).toInteger : 𝓞 K) - 1 ∣
        ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ (a : ZMod p).val - 1 := by
    simpa using
      sub_dvd_pow_sub_pow ((zeta_spec p ℚ K).toInteger : 𝓞 K) (1 : 𝓞 K)
        (a : ZMod p).val
  rw [cyclotomicLambda, zetaPrime, Ideal.mem_span_singleton]
  change ((zeta_spec p ℚ K).toInteger : 𝓞 K) - 1 ∣
    cyclotomicRingOfIntegersEquiv (p := p) K a ((zeta_spec p ℚ K).toInteger - 1)
  rw [map_sub, map_one]
  change ((zeta_spec p ℚ K).toInteger : 𝓞 K) - 1 ∣
    cyclotomicSigmaOfUnit (p := p) K a • (zeta_spec p ℚ K).toInteger - 1
  rw [cyclotomicSigmaOfUnit_smul_zetaInteger]
  exact hdiv

theorem cyclotomicRingOfIntegersEquiv_map_lambda_le (a : CyclotomicUnitDelta p) :
    (cyclotomicLambda p K).map
        (cyclotomicRingOfIntegersEquiv (p := p) K a : 𝓞 K →+* 𝓞 K) ≤
      cyclotomicLambda p K := by
  rw [cyclotomicLambda, zetaPrime, Ideal.map_span, Ideal.span_le]
  rintro x ⟨y, hy, rfl⟩
  simp only [Set.mem_singleton_iff] at hy
  subst hy
  exact cyclotomicRingOfIntegersEquiv_zeta_sub_one_mem_lambda (p := p) (K := K) a

theorem cyclotomicRingOfIntegersEquiv_comap_lambda (a : CyclotomicUnitDelta p) :
    cyclotomicLambda p K =
      (cyclotomicLambda p K).comap
        (cyclotomicRingOfIntegersEquiv (p := p) K a : 𝓞 K →+* 𝓞 K) := by
  ext x
  constructor
  · intro hx
    exact cyclotomicRingOfIntegersEquiv_map_lambda_le (p := p) (K := K) a
      (Ideal.mem_map_of_mem _ hx)
  · intro hx
    rw [Ideal.mem_comap] at hx
    have hinv :
        cyclotomicRingOfIntegersEquiv (p := p) K a⁻¹
            (cyclotomicRingOfIntegersEquiv (p := p) K a x) ∈ cyclotomicLambda p K :=
      cyclotomicRingOfIntegersEquiv_map_lambda_le (p := p) (K := K) a⁻¹
        (Ideal.mem_map_of_mem
          (cyclotomicRingOfIntegersEquiv (p := p) K a⁻¹ : 𝓞 K →+* 𝓞 K) hx)
    have hcomp :
        cyclotomicRingOfIntegersEquiv (p := p) K a⁻¹
            (cyclotomicRingOfIntegersEquiv (p := p) K a x) = x := by
      rw [← cyclotomicRingOfIntegersEquiv_mul_apply]
      simp
    simpa [hcomp] using hinv

end CyclotomicSetup

end Local
end Reflection
end KummerCriterion

end
