module

public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.GaussSum
public import Mathlib.NumberTheory.JacobiSum.Basic
public import Mathlib.RingTheory.Polynomial.Cyclotomic.Eval
public import Mathlib.RingTheory.RootsOfUnity.CyclotomicUnits

/-!
# Stickelberger-style prime factorisation of `g(χ_q)^p` (REF-18c2c)

This file develops the Stickelberger-type theorem for the residue Gauss sum
`g(χ_q, ψ_q)` raised to its character order. The classical statement
(Ireland–Rosen Thm 14.5) gives the explicit prime factorisation of
`g(χ_q)^p` in `𝓞_{K(ζ_{Nq})}`, with exponents controlled by the
Stickelberger weight. We work in stages:

1. **Galois invariance of `g(χ)^n`** (this commit).
   For χ a multiplicative character of order dividing `n`, and a ring hom
   `σ : R' →+* R'` that *fixes* χ (`σ ∘ χ = χ`) and shifts the additive
   character ψ by some `a ∈ Rˣ` (`σ ∘ ψ = AddChar.mulShift ψ a`), the `n`-th
   power `g(χ, ψ)^n` is fixed by `σ`. Proof: `g(χ, AddChar.mulShift ψ a)^n` is
   `(χ a)⁻ⁿ · g(χ, ψ)^n` by `gaussSum_mulShift` raised to `n`, and
   `(χ a)^n = (χ^n) a = 1 a = 1` because `χ^n = 1`.

2. **Application to residue Gauss sums** (this commit).
   For `χ_q` of order `p` (residue character) and any Galois automorphism
   `σ` fixing `K = ℚ(ζ_p)` pointwise (so `σ ∘ χ_q = χ_q`), `g(χ_q, ψ_q)^p`
   is fixed by `σ`.

3. **Prime factorisation via Stickelberger weight** (deferred).
   The actual Stickelberger formula `g(χ_q)^p = q^{p-1} · ∏ σ_a^{?}`
   requires the explicit Galois-orbit computation and Jacobi-sum
   factorisation. This is the core of REF-18c2c and is left for follow-up
   commits.

The Galois-invariance step is small but essential: it shows that
`g(χ_q, ψ_q)^p` *descends* from the larger ring `R' = K(ζ_{Nq})` to the
fixed field of the appropriate Galois group, which in our application
will be `K = ℚ(ζ_p)`. This is the key feature exploited by the
Stickelberger formula's prime factorisation.
-/

@[expose] public section

noncomputable section

namespace BernoulliRegular

namespace Furtwaengler

variable {R : Type*} [CommRing R] [Fintype R]
variable {R' : Type*} [CommRing R']










/-!
### Subring descent: `J(χ_q, χ_q^i)` lies in `Subring.closure {ζ_R}`

Each Jacobi sum `J(χ_q, χ_q^i) = -∑_x χ_q(x) χ_q^i(1-x)` is a finite ℤ-linear
combination of products of values of `χ_q`. Since `χ_q` takes values in
`{0} ∪ μ_p`, all of which lie in the subring `ℤ[ζ_R]` generated by `ζ_R`,
each Jacobi sum lies in this subring. This formalises the descent of
`g(χ_q)^p = χ_q(-1) · #k · ∏ J(χ_q, χ_q^i)` from the ambient ring `R'` to
the smaller subring `Subring.closure {ζ_R}` — which is `ℤ[ζ_p]` in the
intended cyclotomic application, and equals `𝓞_K` for `K = ℚ(ζ_p)`.
-/

/-!
### q-adic valuation of `g(χ_q)` (REF-18c2c2 — abstract form)

The classical Stickelberger argument proves `g(χ_q) ∈ P` for `P` a prime
ideal of `𝓞_{R'}` above the rational prime `q`, by reducing the Gauss
sum modulo `P` and using that `ζ_q ≡ 1 (mod P)` plus the vanishing of
non-trivial character sums.

We package this as a clean abstract lemma: if any ideal `I ⊆ R'` contains
`ψ(x) - 1` for all `x : R`, then it contains `gaussSum χ ψ` (for `χ ≠ 1`).
The concrete instantiation `I = P, ψ_q(x) - 1 = (ζ_q^{Tr(x)} - 1) ∈ P`
is the content of a later subticket since it requires concrete cyclotomic
extension scaffolding.
-/

/-- **Algebraic helper for the concrete instantiation of REF-18c2c2.**
If `x - 1 ∈ I`, then `x^n - 1 ∈ I` for all `n`. Useful when verifying the
hypothesis of `gaussSum_mem_ideal_of_addChar_sub_one_mem` for the concrete
additive character `ψ_q(x) = ζ_q^{Tr(x)}`: assuming `ζ_q - 1 ∈ P` (the
cyclotomic ramification fact for `P` above `q`), this gives
`ψ_q(x) - 1 = ζ_q^{Tr(x)} - 1 ∈ P` for all `x`. -/
theorem pow_sub_one_mem_of_sub_one_mem
    {R : Type*} [CommRing R] (x : R) (n : ℕ)
    {I : Ideal R} (h : x - 1 ∈ I) :
    x ^ n - 1 ∈ I := by
  obtain ⟨c, hc⟩ := sub_one_dvd_pow_sub_one x n
  rw [hc]
  exact Ideal.mul_mem_right _ _ h



/-!
### Galois orbit of `g(χ_q)` (REF-18c2c3 — abstract form)

Combining `residueGaussSum_ringHomComp` (REF-18c2b) with the character
compatibility `residueMulChar_ringHomComp_pow_eq` above gives the
*abstract Galois orbit identity*: for any ring hom `σ : R' →+* R'`
sending `ζ_R ↦ ζ_R^a`,

  `σ(g(χ_q, ψ_q)) = g(χ_q^a, σ ∘ ψ_q)`.

In the concrete cyclotomic application (`R' = K(ζ_q)` and σ_a the
Galois automorphism with `ζ_q ↦ ζ_q^a`), the additive character
transforms as `(σ_a · ψ_q)(x) = ψ_q(a·x)`; the substitution `y = a·x`
then converts the right-hand side into a multiple of `g(χ_q^a, ψ_q)`
controlled by `χ_q^a(a^{-1})`. That refinement requires the concrete
trace formula `ψ_q(x) = ζ_q^{Tr(x)}` and is deferred to REF-18c2c4
together with the prime-ideal factorisation work.
-/






/-- Generic lemma: if `y` is integral over `ℤ` and `x ∈ Subring.closure {y}`,
then `x` is integral over `ℤ`. The integral closure is itself a subring,
containing `y`, hence contains `Subring.closure {y}`. -/
private theorem isIntegral_of_mem_closure_singleton
    {R' : Type*} [CommRing R'] {y : R'} (hy : IsIntegral ℤ y)
    {x : R'} (hx : x ∈ Subring.closure {y}) :
    IsIntegral ℤ x := by
  refine Subring.closure_induction
    (p := fun x _ => IsIntegral ℤ x) ?_ ?_ ?_ ?_ ?_ ?_ hx
  · intro z hz
    rw [Set.mem_singleton_iff] at hz
    exact hz ▸ hy
  · exact isIntegral_zero
  · exact isIntegral_one
  · exact fun _ _ _ _ ha hb => ha.add hb
  · exact fun _ _ ha => ha.neg
  · exact fun _ _ _ _ ha hb => ha.mul hb



/-!
### Stickelberger weight

The integer-valued exponent appearing in the prime factorisation of
`g(χ_q^a)`: for `1 ≤ a ≤ p - 1`, this is `a · ((Nq - 1) / p)`, which counts
the contribution of the `a`-th Galois conjugate to the q-adic valuation
of the residue Gauss sum. The full Stickelberger formula combines these
weights over all conjugates.
-/






/-!
### `p`-th-power Gauss-sum norm, ideal form

The conjugate-pair relation `g(χ_q) · g(χ_q^{p-1}) = χ_q(-1) · #k` raised
to the `p`-th power, combined with `χ_q(-1)^p = 1`, gives an "ideal-form"
norm: `g(χ_q)^p · g(χ_q^{p-1})^p = (#k)^p`. This is the integer-level
divisibility precursor to the prime-ideal-level Stickelberger formula.
-/



/-!
### Abstract consequences for prime ideal factorisation (REF-18c2c4 — Phase A)

The full Stickelberger prime ideal factorisation requires concrete cyclotomic
ramification machinery (a chosen extension `R'` containing both `μ_p` and
`μ_q`, identification of the prime ideals above `q`, and the ramification fact
`(ζ_q − 1)^{q−1} ∼ q`). Before tackling that infrastructure, we collect the
algebraic consequences that follow purely from the existing abstract API.

These lemmas are useful in the eventual concrete formula and help isolate the
genuinely "cyclotomic-arithmetic" content from the underlying ring theory.
-/




/-!
### Cyclotomic ramification (REF-18c2c4 — Phase B)

The classical ramification fact: in any commutative domain `R` containing a
primitive `q`-th root of unity `ζ` (with `q` a rational prime), every prime
ideal `Q` of `R` containing `q` also contains `ζ - 1`.

This is the algebraic content of `(ζ - 1)^{q-1} ∼ q` (the cyclotomic
ramification of `q` in `ℤ[ζ_q]`), formulated at the prime-ideal level.
The proof uses the polynomial identity `Φ_q(1) = q` together with the
factorisation `Φ_q = ∏_{μ primitive} (X - C μ)` and the associate-class
identification of `ζ - 1` with each `ζ^j - 1` for `j` coprime to `q`.

Combined with REF-18c2c2's `gaussSum_mem_ideal_of_addChar_sub_one_mem`,
this gives the concrete instantiation: `g(χ_q) ∈ Q` for `Q` above `q`,
when the additive character `ψ_q` has the form `ψ_q(x) = ζ^{Tr(x)}`.
-/

/-- **Membership preservation under associated elements.** In a commutative
ring, two associated elements lie in the same ideals. -/
private theorem _root_.Associated.mem_ideal_of_mem
    {R : Type*} [CommRing R] {a b : R} (h : Associated a b)
    {I : Ideal R} (ha : a ∈ I) :
    b ∈ I := by
  obtain ⟨u, rfl⟩ := h
  exact Ideal.mul_mem_right (u : R) I ha


end Furtwaengler

end BernoulliRegular
