module

public import KummerCriterion.TotallyRealSubfield.Basic

/-!
# `ζ_p - 1` prime arithmetic

This file packages the distinguished prime above `p`, its contraction to
`K⁺`, and the even-valuation / ramification facts needed later in the class
group descent.
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField Algebra IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace KummerCriterion

section CyclotomicSetup

variable (p : ℕ) [hp : Fact p.Prime] (hp_odd : p ≠ 2)
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

theorem zeta_toInteger_pow_eq_one :
    ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ p = 1 := by
  apply RingOfIntegers.ext
  push_cast
  exact (zeta_spec p ℚ K).pow_eq_one

/-- `ζ^{p-1} · ζ = 1`, i.e. `ζ⁻¹ = ζ^{p-1}`. -/
theorem zeta_toInteger_pow_pred_mul :
    ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ (p - 1) *
      ((zeta_spec p ℚ K).toInteger : 𝓞 K) = 1 := by
  rw [← pow_succ, Nat.sub_one_add_one hp.1.ne_zero]
  exact zeta_toInteger_pow_eq_one p K

/-- The unique prime above `p` in `𝓞 K`, generated by `ζ - 1` for the
distinguished primitive `p`-th root of unity
`ζ = IsCyclotomicExtension.zeta p ℚ K`. -/
noncomputable def zetaPrime : Ideal (𝓞 K) :=
  Ideal.span {((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K)}

instance zetaPrime_isPrime : (zetaPrime p K).IsPrime :=
  (Ideal.span_singleton_prime
    (zeta_spec p ℚ K).zeta_sub_one_prime'.ne_zero).mpr
    (zeta_spec p ℚ K).zeta_sub_one_prime'

/-- `zetaPrime` is nonzero. -/
theorem zetaPrime_ne_bot : zetaPrime p K ≠ ⊥ := by
  rw [zetaPrime, Ne, Ideal.span_singleton_eq_bot]
  exact (zeta_spec p ℚ K).zeta_sub_one_prime'.ne_zero

/-- The contraction of `𝔓` to `𝓞_{K⁺}` — the prime of `𝓞_{K⁺}` below `𝔓`. -/
noncomputable def zetaPrimePlus [IsCMField K] : Ideal (𝓞 (K⁺)) :=
  (zetaPrime p K).under (𝓞 (K⁺))

instance [IsCMField K] : (zetaPrimePlus p K).IsPrime :=
  Ideal.IsPrime.under _ _

instance [IsCMField K] : (zetaPrime p K).LiesOver (zetaPrimePlus p K) :=
  Ideal.over_under _

/-- On the distinguished root of unity, `c(ζ) = ζ^{p-1}` as integers.
This is the key algebraic identity making `c` act on 𝓞 K. -/
lemma complexConj_apply_zeta [IsCMField K] :
    (ringOfIntegersComplexConj K (zeta_spec p ℚ K).toInteger : 𝓞 K) =
      ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ (p - 1) := by
  have hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  have hzeta_torsion : hζ.unit' ∈ NumberField.Units.torsion K :=
    (CommGroup.mem_torsion _ _).2
      (isOfFinOrder_iff_pow_eq_one.2 ⟨p, hp.1.pos, hζ.unit'_pow⟩)
  have hconj := unitsComplexConj_torsion (K := K) ⟨hζ.unit', hzeta_torsion⟩
  have h1 : (unitsComplexConj K hζ.unit' : 𝓞 K) = (hζ.unit'⁻¹ : (𝓞 K)ˣ) :=
    congrArg ((↑·) : (𝓞 K)ˣ → 𝓞 K) hconj
  have h2 : (hζ.unit'⁻¹ : (𝓞 K)ˣ) = hζ.unit' ^ (p - 1) := by
    apply inv_eq_of_mul_eq_one_left
    rw [← pow_succ, Nat.sub_one_add_one hp.1.ne_zero]
    ext; push_cast; exact hζ.pow_eq_one
  rw [show (ringOfIntegersComplexConj K hζ.toInteger : 𝓞 K) =
    (unitsComplexConj K hζ.unit' : 𝓞 K) from rfl, h1, h2, Units.val_pow_eq_pow_val]
  rfl

/-- Complex conjugation `c` acts as the identity on the residue field
`𝓞 K / 𝔓`: equivalently, `c(x) ≡ x (mod 𝔓)` for every `x : 𝓞 K`. -/
theorem complexConj_sub_mem_zetaPrime [IsCMField K] (x : 𝓞 K) :
    (ringOfIntegersComplexConj K x : 𝓞 K) - x ∈ zetaPrime p K := by
  have hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  have htop : Algebra.adjoin ℤ {hζ.toInteger} = ⊤ :=
    IsCyclotomicExtension.Rat.adjoin_singleton_eq_top hζ
  have hx : x ∈ Algebra.adjoin ℤ ({hζ.toInteger} : Set (𝓞 K)) := htop ▸ trivial
  induction hx using Algebra.adjoin_induction with
  | mem y hy =>
    simp only [Set.mem_singleton_iff] at hy
    subst hy
    have hp_pow : hζ.toInteger ^ p = 1 := zeta_toInteger_pow_eq_one p K
    have hc_pow : (ringOfIntegersComplexConj K hζ.toInteger) ^ p = 1 := by
      rw [← map_pow, hp_pow, map_one]
    have hmem_of_pow : ∀ μ : 𝓞 K, μ ^ p = 1 → μ - 1 ∈ zetaPrime p K := by
      intro μ hμ
      have h1 := hζ.unit'_coe.eq_one_mod_sub_of_pow hμ
      have h2 : (algebraMap (𝓞 K)
          (𝓞 K ⧸ Ideal.span ({(hζ.unit' : 𝓞 K) - 1} : Set (𝓞 K)))) (μ - 1) = 0 := by
        rw [map_sub, h1, map_one, sub_self]
      rw [Ideal.Quotient.algebraMap_eq, Ideal.Quotient.eq_zero_iff_mem] at h2
      exact h2
    have h1 : (hζ.toInteger : 𝓞 K) - 1 ∈ zetaPrime p K := hmem_of_pow _ hp_pow
    have h2 : (ringOfIntegersComplexConj K hζ.toInteger : 𝓞 K) - 1 ∈ zetaPrime p K :=
      hmem_of_pow _ hc_pow
    have : (ringOfIntegersComplexConj K hζ.toInteger : 𝓞 K) - hζ.toInteger =
        ((ringOfIntegersComplexConj K hζ.toInteger : 𝓞 K) - 1) -
          (hζ.toInteger - 1) := by ring
    rw [this]
    exact Ideal.sub_mem _ h2 h1
  | algebraMap r =>
    have : ringOfIntegersComplexConj K ((algebraMap ℤ (𝓞 K)) r) =
        (algebraMap ℤ (𝓞 K)) r := by
      rw [IsScalarTower.algebraMap_apply ℤ (𝓞 (K⁺)) (𝓞 K), AlgEquiv.commutes]
    rw [this, sub_self]
    exact Ideal.zero_mem _
  | add x y _ _ hpx hpy =>
    have : (ringOfIntegersComplexConj K (x + y) : 𝓞 K) - (x + y) =
        ((ringOfIntegersComplexConj K x : 𝓞 K) - x) +
          ((ringOfIntegersComplexConj K y : 𝓞 K) - y) := by
      push_cast [map_add]; ring
    rw [this]
    exact Ideal.add_mem _ hpx hpy
  | mul x y _ _ hpx hpy =>
    have : (ringOfIntegersComplexConj K (x * y) : 𝓞 K) - (x * y) =
        ((ringOfIntegersComplexConj K x : 𝓞 K) - x) *
            (ringOfIntegersComplexConj K y : 𝓞 K) +
          x * ((ringOfIntegersComplexConj K y : 𝓞 K) - y) := by
      push_cast [map_mul]; ring
    rw [this]
    exact Ideal.add_mem _
      (Ideal.mul_mem_right _ _ hpx)
      (Ideal.mul_mem_left _ _ hpy)

/-- Key algebraic identity: `π · c(π) = -ζ^{p-1} · π²` in `𝓞 K`, where
`π = ζ - 1`. Consequence: `π · c(π)` is associate to `π²`. -/
lemma pi_mul_complexConj_pi_eq [IsCMField K] :
    ((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K) *
      ringOfIntegersComplexConj K ((zeta_spec p ℚ K).toInteger - 1) =
      -((zeta_spec p ℚ K).toInteger ^ (p - 1)) *
        ((zeta_spec p ℚ K).toInteger - 1) ^ 2 := by
  have hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  have hc_pi : (ringOfIntegersComplexConj K (hζ.toInteger - 1) : 𝓞 K) =
      hζ.toInteger ^ (p - 1) - 1 := by
    rw [map_sub, map_one, complexConj_apply_zeta]
  have hpow_succ : hζ.toInteger ^ (p - 1) * hζ.toInteger = 1 :=
    zeta_toInteger_pow_pred_mul p K
  rw [hc_pi]
  linear_combination (hζ.toInteger - 1) * hpow_succ

/-- `π · c(π)` is fixed by complex conjugation, hence lies in `𝓞_{K⁺}`. -/
lemma complexConj_pi_mul_complexConj_pi [IsCMField K] :
    ringOfIntegersComplexConj K
        (((zeta_spec p ℚ K).toInteger - 1) *
          ringOfIntegersComplexConj K ((zeta_spec p ℚ K).toInteger - 1)) =
      ((zeta_spec p ℚ K).toInteger - 1) *
        ringOfIntegersComplexConj K ((zeta_spec p ℚ K).toInteger - 1) := by
  rw [map_mul, mul_comm]
  congr 1
  ext
  exact complexConj_apply_apply K _

/-- The real uniformizer `piPlus: 𝓞_{K⁺}`, whose image in `𝓞 K` is `π · c(π)`. -/
noncomputable def piPlus [IsCMField K] : 𝓞 (K⁺) := by
  have hfix := complexConj_pi_mul_complexConj_pi p K
  rw [RingOfIntegers.ext_iff, coe_ringOfIntegersComplexConj,
    RingOfIntegers.complexConj_eq_self_iff] at hfix
  exact hfix.choose

lemma algebraMap_piPlus [IsCMField K] :
    (algebraMap (𝓞 (K⁺)) (𝓞 K)) (piPlus p K) =
      ((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K) *
        ringOfIntegersComplexConj K ((zeta_spec p ℚ K).toInteger - 1) := by
  have hfix := complexConj_pi_mul_complexConj_pi p K
  rw [RingOfIntegers.ext_iff, coe_ringOfIntegersComplexConj,
    RingOfIntegers.complexConj_eq_self_iff] at hfix
  ext
  rw [← hfix.choose_spec]; rfl

/-- `(piPlus) · 𝓞 K = 𝔓²`. Concrete form of the ramification fact
`e(𝔓 | 𝔓⁺) = 2`. -/
theorem map_span_piPlus_eq_zetaPrime_sq [IsCMField K] :
    (Ideal.span {piPlus p K}).map (algebraMap (𝓞 (K⁺)) (𝓞 K)) =
      zetaPrime p K ^ 2 := by
  have hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  have hζ_unit : IsUnit ((hζ.unit' : 𝓞 K) ^ (p - 1)) := (hζ.unit'.isUnit.pow _)
  have hneg_unit : IsUnit (-(hζ.toInteger : 𝓞 K) ^ (p - 1)) := by
    rw [show (hζ.toInteger : 𝓞 K) = (hζ.unit' : 𝓞 K) from rfl]
    exact hζ_unit.neg
  rw [Ideal.map_span, Set.image_singleton, algebraMap_piPlus,
    pi_mul_complexConj_pi_eq, zetaPrime, Ideal.span_singleton_pow,
    show -(hζ.toInteger : 𝓞 K) ^ (p - 1) * ((hζ.toInteger - 1) ^ 2) =
        ((hζ.toInteger - 1) ^ 2) * -(hζ.toInteger) ^ (p - 1) from by ring,
    Ideal.span_singleton_mul_right_unit hneg_unit]

include hp_odd in
/-- Key ramification fact (element form): for every non-zero `x ∈ 𝓞_{K⁺}`,
the `π`-adic multiplicity of its image in `𝓞 K` is **even**. -/
theorem multiplicity_zetaPrime_algebraMap_even [IsCMField K]
    (x : 𝓞 (K⁺)) (hx : x ≠ 0) :
    Even (multiplicity ((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K)
                      (algebraMap (𝓞 (K⁺)) (𝓞 K) x)) := by
  have hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  set α := algebraMap (𝓞 (K⁺)) (𝓞 K) x with hα_def
  have hα : α ≠ 0 := (map_ne_zero_iff _ (FaithfulSMul.algebraMap_injective _ _)).mpr hx
  have hπ_prime : Prime (hζ.toInteger - 1 : 𝓞 K) := hζ.zeta_sub_one_prime'
  have hfin : FiniteMultiplicity (hζ.toInteger - 1 : 𝓞 K) α :=
    FiniteMultiplicity.of_prime_left hπ_prime hα
  obtain ⟨u, hαu, hπ_nd_u⟩ := hfin.exists_eq_pow_mul_and_not_dvd
  set e := multiplicity (hζ.toInteger - 1 : 𝓞 K) α with he_def
  have hcα : ringOfIntegersComplexConj K α = α :=
    (ringOfIntegersComplexConj K).commutes x
  have hc_pi : ringOfIntegersComplexConj K (hζ.toInteger - 1) =
      -hζ.toInteger ^ (p - 1) * (hζ.toInteger - 1) := by
    rw [map_sub, map_one, complexConj_apply_zeta]
    linear_combination zeta_toInteger_pow_pred_mul p K
  have hcα_expand : (-hζ.toInteger ^ (p - 1) * (hζ.toInteger - 1) : 𝓞 K) ^ e *
      ringOfIntegersComplexConj K u = (hζ.toInteger - 1) ^ e * u := by
    have := hcα
    rw [hαu, map_mul, map_pow, hc_pi] at this
    exact this
  have hπ_ne : (hζ.toInteger - 1 : 𝓞 K) ≠ 0 := hπ_prime.ne_zero
  have hcu_eq : ((-hζ.toInteger ^ (p - 1)) ^ e : 𝓞 K) * ringOfIntegersComplexConj K u = u := by
    have hreord : ((hζ.toInteger - 1) ^ e : 𝓞 K) *
        (((-hζ.toInteger ^ (p - 1)) ^ e) * ringOfIntegersComplexConj K u) =
        ((hζ.toInteger - 1) ^ e : 𝓞 K) * u := by
      have hsplit : ((-hζ.toInteger ^ (p - 1) * (hζ.toInteger - 1)) ^ e : 𝓞 K) =
          ((hζ.toInteger - 1) ^ e) * (((-hζ.toInteger ^ (p - 1)) ^ e)) := by
        rw [mul_pow]; ring
      rw [← hcα_expand, hsplit, mul_assoc]
    exact mul_left_cancel₀ (pow_ne_zero _ hπ_ne) hreord
  have hres : (ringOfIntegersComplexConj K u : 𝓞 K) - u ∈ zetaPrime p K :=
    complexConj_sub_mem_zetaPrime p K u
  have hpow_sub : ∀ n : ℕ, (hζ.toInteger ^ n - 1 : 𝓞 K) ∈ zetaPrime p K := by
    intro n
    rw [zetaPrime, Ideal.mem_span_singleton]
    have := sub_dvd_pow_sub_pow hζ.toInteger (1 : 𝓞 K) n
    rwa [one_pow] at this
  have hneg_pow_sub : ((-hζ.toInteger ^ (p - 1)) ^ e - (-1) ^ e : 𝓞 K) ∈ zetaPrime p K := by
    have key : ((-hζ.toInteger ^ (p - 1)) ^ e - (-1) ^ e : 𝓞 K) =
        (-1) ^ e * (hζ.toInteger ^ ((p - 1) * e) - 1) := by
      rw [neg_pow, ← pow_mul]; ring
    rw [key]
    exact Ideal.mul_mem_left _ _ (hpow_sub _)
  have hkey : ((1 - (-1) ^ e) * u : 𝓞 K) ∈ zetaPrime p K := by
    have h1 : ((-hζ.toInteger ^ (p - 1)) ^ e : 𝓞 K) * ringOfIntegersComplexConj K u -
        (-1) ^ e * u ∈ zetaPrime p K := by
      have h1a : ((-hζ.toInteger ^ (p - 1)) ^ e : 𝓞 K) * ringOfIntegersComplexConj K u -
          (-1) ^ e * u =
          (((-hζ.toInteger ^ (p - 1)) ^ e - (-1) ^ e) * ringOfIntegersComplexConj K u) +
          ((-1) ^ e) * (ringOfIntegersComplexConj K u - u) := by ring
      rw [h1a]
      exact Ideal.add_mem _
        (Ideal.mul_mem_right _ _ hneg_pow_sub)
        (Ideal.mul_mem_left _ _ hres)
    rw [hcu_eq] at h1
    convert h1 using 1
    ring
  rcases Nat.even_or_odd e with he | he
  · exact he
  · exfalso
    have hp2 : 2 < p := lt_of_le_of_ne hp.1.two_le (Ne.symm hp_odd)
    have h_two_u : (2 * u : 𝓞 K) ∈ zetaPrime p K := by
      convert hkey using 2
      rw [Odd.neg_one_pow he]; ring
    have h_prime := zetaPrime_isPrime p K
    rcases h_prime.mem_or_mem h_two_u with h | h
    · exact (zeta_spec p ℚ K).two_not_mem_one_sub_zeta hp2 h
    · rw [zetaPrime, Ideal.mem_span_singleton] at h
      exact hπ_nd_u h

include hp_odd in
/-- **Ramification fact (ideal form):** `𝔓⁺ · 𝓞 K = 𝔓²`. -/
theorem zetaPrimePlus_map_eq [IsCMField K] :
    (zetaPrimePlus p K).map (algebraMap (𝓞 (K⁺)) (𝓞 K)) = (zetaPrime p K) ^ 2 := by
  refine le_antisymm ?_ ?_
  · rw [Ideal.map_le_iff_le_comap]
    intro y hy
    rw [zetaPrimePlus] at hy
    rw [Ideal.mem_comap, zetaPrime, Ideal.mem_span_singleton] at hy
    by_cases hy0 : y = 0
    · simp [hy0]
    have heven := multiplicity_zetaPrime_algebraMap_even p hp_odd K y hy0
    have hfin : FiniteMultiplicity
        ((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K)
        (algebraMap (𝓞 (K⁺)) (𝓞 K) y) :=
      FiniteMultiplicity.of_prime_left (zeta_spec p ℚ K).zeta_sub_one_prime'
        ((map_ne_zero_iff _ (FaithfulSMul.algebraMap_injective _ _)).mpr hy0)
    have hge : 1 ≤ multiplicity ((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K)
        (algebraMap (𝓞 (K⁺)) (𝓞 K) y) := by
      apply hfin.pow_dvd_iff_le_multiplicity.mp
      rw [pow_one]
      exact hy
    have h2le : 2 ≤ multiplicity ((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K)
        (algebraMap (𝓞 (K⁺)) (𝓞 K) y) := by
      rcases heven with ⟨k, hk⟩
      omega
    rw [Ideal.mem_comap, show (zetaPrime p K) ^ 2 =
        Ideal.span {((zeta_spec p ℚ K).toInteger - 1 : 𝓞 K) ^ 2} from
      by rw [zetaPrime, Ideal.span_singleton_pow], Ideal.mem_span_singleton]
    exact hfin.pow_dvd_iff_le_multiplicity.mpr h2le
  · rw [← map_span_piPlus_eq_zetaPrime_sq p K]
    refine Ideal.map_mono ?_
    rw [Ideal.span_singleton_le_iff_mem]
    rw [zetaPrimePlus, Ideal.mem_comap, zetaPrime, algebraMap_piPlus,
      Ideal.mem_span_singleton]
    exact dvd_mul_right _ _

end CyclotomicSetup

end KummerCriterion

end
