module

public import KummerCriterion.PrimitiveRootUnits
import Mathlib.Analysis.SpecialFunctions.Bernstein
import Mathlib.RingTheory.RootsOfUnity.CyclotomicUnits
import KummerCriterion.TotallyRealSubfield.ZetaPrime
public import Mathlib.NumberTheory.NumberField.CMField

/-!
# Primary elements of cyclotomic rings of integers

For a prime `p`, an element `α ∈ 𝒪_K` of the cyclotomic ring is **primary**
when it is congruent to a rational integer modulo `(ζ - 1)^{2p}`. Following
Vandiver, this is the standard hypothesis under which an `ℓ`-th power ideal
generated by `α` descends through complex conjugation.

This file isolates the definition `IsPrimary` and its basic lemmas.

## References

* Washington, *Introduction to Cyclotomic Fields*, §6.4 (definition).
* Borevich–Shafarevich, *Number Theory*, §4.9 (use in Vandiver Lemma 1).
* `FltRegular.NumberTheory.Cyclotomic.MoreLemmas`
 (`zeta_sub_one_dvd_Int_iff`, `exists_zeta_sub_one_dvd_sub_Int`).
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace KummerCriterion

namespace LehmerVandiver

section CyclotomicSetup

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

local notation3 "ζ" => IsCyclotomicExtension.zeta p ℚ K

/-- The element `ζ - 1 ∈ 𝒪_K`, where `ζ` is the standard primitive `p`-th
root of unity supplied by `IsCyclotomicExtension`. This is a uniformizer at
the unique prime above `p`. -/
noncomputable def zetaSubOne : 𝓞 K :=
  (zeta_spec p ℚ K).unit' - 1

end CyclotomicSetup

end LehmerVandiver

end KummerCriterion

end

/-!
# Complex conjugation preserves primarity

For a CM cyclotomic field `K = ℚ(ζ_p)`, complex conjugation `σ` sends `ζ` to
`ζ^{p-1}`. Hence `σ(ζ - 1) = ζ^{p-1} - 1 = -ζ^{p-1}(ζ - 1)`, and `σ(ζ - 1)`
is associated to `ζ - 1`. Divisibility by `(ζ - 1)^k` is therefore preserved
by `σ`, and primarity is `σ`-invariant.

The arithmetic input
`(ζ - 1)^{2p} ∣ α - σ(α)` (`zetaSubOne_pow_dvd_sub_complexConj`) is the entry
point for showing `[(α)] = [(σ(α))]` in `Cl(K)`, the Galois descent step
toward Vandiver Lemma 1.

## References

* Washington, *Introduction to Cyclotomic Fields*, §6.4.
* `KummerCriterion.TotallyRealSubfield.Conjugation`
 (`complexConj_apply_zeta`).
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace KummerCriterion

namespace LehmerVandiver

section ConjSetup

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The unit `-ζ^{p-1} ∈ (𝓞 K)ˣ` realising the associated relation
`σ(ζ - 1) = (-ζ^{p-1}) (ζ - 1)`. -/
noncomputable def zetaSubOneConjUnit : (𝓞 K)ˣ :=
  (-1 : (𝓞 K)ˣ) * (zeta_spec p ℚ K).unit' ^ (p - 1)

omit [NumberField K] in
private theorem coe_neg_one_unit : ((-1 : (𝓞 K)ˣ) : 𝓞 K) = -1 := rfl

private theorem coe_unit'_eq_toInteger :
    ((zeta_spec p ℚ K).unit' : 𝓞 K) = (zeta_spec p ℚ K).toInteger :=
  rfl

/-- Complex conjugation multiplies `ζ - 1` by `-ζ^{p-1}`. -/
theorem complexConj_zetaSubOne_eq [IsCMField K] :
    ringOfIntegersComplexConj K (zetaSubOne p K) =
      ((zetaSubOneConjUnit p K : (𝓞 K)ˣ) : 𝓞 K) * zetaSubOne p K := by
  have hζ_pow : (zeta_spec p ℚ K).toInteger ^ p = 1 := zeta_toInteger_pow_eq_one p K
  have hconj_zeta : (ringOfIntegersComplexConj K (zeta_spec p ℚ K).toInteger : 𝓞 K) =
      ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ (p - 1) :=
    complexConj_apply_zeta (p := p) (K := K)
  have hp1 : p - 1 + 1 = p := Nat.sub_add_cancel hp.1.one_lt.le
  have key : ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ (p - 1) *
      (zeta_spec p ℚ K).toInteger = 1 := by
    rw [← pow_succ, hp1]; exact hζ_pow
  have lhs_eq : ringOfIntegersComplexConj K (zetaSubOne p K) =
      ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ (p - 1) - 1 := by
    change ringOfIntegersComplexConj K ((zeta_spec p ℚ K).unit' - 1) = _
    rw [map_sub, map_one, coe_unit'_eq_toInteger, hconj_zeta]
  have rhs_eq : ((zetaSubOneConjUnit p K : (𝓞 K)ˣ) : 𝓞 K) * zetaSubOne p K =
      ((zeta_spec p ℚ K).toInteger : 𝓞 K) ^ (p - 1) - 1 := by
    change (((-1 : (𝓞 K)ˣ) * (zeta_spec p ℚ K).unit' ^ (p - 1) : (𝓞 K)ˣ) : 𝓞 K) *
        ((zeta_spec p ℚ K).unit' - 1) = _
    rw [Units.val_mul, Units.val_pow_eq_pow_val, coe_neg_one_unit, coe_unit'_eq_toInteger]
    linear_combination -key
  rw [lhs_eq, rhs_eq]

/-- `σ(ζ - 1)` is associated to `ζ - 1` in `𝓞 K`. -/
theorem associated_complexConj_zetaSubOne [IsCMField K] :
    Associated (zetaSubOne p K) (ringOfIntegersComplexConj K (zetaSubOne p K)) :=
  ⟨zetaSubOneConjUnit p K, by rw [complexConj_zetaSubOne_eq]; ring⟩

end ConjSetup

end LehmerVandiver

end KummerCriterion

end

/-!
# Primary units of `𝓞 K⁺`

For Vandiver Lemma 2 (primary unit decomposition), an element
`γ ∈ 𝓞 K⁺` is **primary** when it is congruent to a rational integer
modulo `𝔭⁺^p`, where `𝔭⁺` is the unique prime of `𝓞 K⁺` above `(p)`.
Equivalently (since `𝔭⁺·𝓞 K = 𝔭² = (ζ-1)^2`), this is
`γ ≡ a (mod (ζ-1)^{2p})` viewed in `𝓞 K`.

This file isolates the K⁺-side primary definition with basic API.

## References

* Washington, *Introduction to Cyclotomic Fields*, §6.4.
* Vandiver 1929, *Fermat's Last Theorem and the Second Factor in the
 Cyclotomic Class Number*.
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField IsCyclotomicExtension
open scoped NumberField

namespace KummerCriterion

namespace LehmerVandiver

section PrimaryPlus

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

section CyclotomicUnits

variable (p : ℕ) [hp : Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The cyclotomic unit `(1 - ζ^k)/(1 - ζ) ∈ 𝓞 K` for `k` coprime to
`p`. Equivalently `1 + ζ + ζ^2 +... + ζ^{k-1}`. -/
noncomputable def cyclotomicUnit (k : ℕ) : 𝓞 K :=
  ∑ j ∈ Finset.range k, (zeta_spec p ℚ K).unit' ^ j

/-- Recursive identity: `cyclotomicUnit (k+1) = cyclotomicUnit k + ζ^k`. -/
theorem cyclotomicUnit_succ (k : ℕ) :
    cyclotomicUnit p K (k + 1) =
      cyclotomicUnit p K k + ((zeta_spec p ℚ K).unit' : 𝓞 K) ^ k :=
  Finset.sum_range_succ _ _

/-- The cyclotomic-unit telescoping identity:
`(1 - ζ) · cyclotomicUnit k = 1 - ζ^k` in `𝓞 K`. -/
theorem one_sub_zeta_mul_cyclotomicUnit (k : ℕ) :
    (1 - (zeta_spec p ℚ K).unit') * cyclotomicUnit p K k =
      1 - ((zeta_spec p ℚ K).unit' : 𝓞 K) ^ k := by
  unfold cyclotomicUnit
  rw [Finset.mul_sum]
  induction k with
  | zero => simp
  | succ n ih =>
    rw [Finset.sum_range_succ, ih]
    ring

/-- Reversed sign form: `(ζ - 1) · cyclotomicUnit k = ζ^k - 1`. -/
theorem zeta_sub_one_mul_cyclotomicUnit (k : ℕ) :
    (((zeta_spec p ℚ K).unit' : 𝓞 K) - 1) * cyclotomicUnit p K k =
      ((zeta_spec p ℚ K).unit' : 𝓞 K) ^ k - 1 := by
  linear_combination -(one_sub_zeta_mul_cyclotomicUnit p K k)

/-- `cyclotomicUnit k ≡ k (mod ζ - 1)` in `𝓞 K`: the difference
`cyclotomicUnit k - k` is divisible by `ζ - 1`. -/
theorem zetaSubOne_dvd_cyclotomicUnit_sub_natCast (k : ℕ) :
    ((zeta_spec p ℚ K).unit' : 𝓞 K) - 1 ∣
      cyclotomicUnit p K k - (k : 𝓞 K) := by
  unfold cyclotomicUnit
  induction k with
  | zero => simp
  | succ n ih =>
    rw [Finset.sum_range_succ]
    have hcast : ((n + 1 : ℕ) : 𝓞 K) = (n : 𝓞 K) + 1 := by push_cast; rfl
    rw [hcast]
    have hsplit : ∑ j ∈ Finset.range n, ((zeta_spec p ℚ K).unit' : 𝓞 K) ^ j +
        ((zeta_spec p ℚ K).unit' : 𝓞 K) ^ n - ((n : 𝓞 K) + 1) =
        (∑ j ∈ Finset.range n, ((zeta_spec p ℚ K).unit' : 𝓞 K) ^ j - (n : 𝓞 K)) +
        (((zeta_spec p ℚ K).unit' : 𝓞 K) ^ n - 1) := by ring
    rw [hsplit]
    refine dvd_add ih ?_
    exact ⟨cyclotomicUnit p K n, (zeta_sub_one_mul_cyclotomicUnit p K n).symm⟩

/-- The complex conjugate of `cyclotomicUnit k` is also congruent to `k`
modulo `ζ - 1`. -/
theorem zetaSubOne_dvd_complexConj_cyclotomicUnit_sub_natCast [IsCMField K] (k : ℕ) :
    ((zeta_spec p ℚ K).unit' : 𝓞 K) - 1 ∣
      ringOfIntegersComplexConj K (cyclotomicUnit p K k) - (k : 𝓞 K) := by
  have h := zetaSubOne_dvd_cyclotomicUnit_sub_natCast p K k
  have h_apply :
      ringOfIntegersComplexConj K (((zeta_spec p ℚ K).unit' : 𝓞 K) - 1) ∣
      ringOfIntegersComplexConj K (cyclotomicUnit p K k - (k : 𝓞 K)) :=
    map_dvd (ringOfIntegersComplexConj K).toRingEquiv.toRingHom h
  rw [map_sub, map_sub (a := cyclotomicUnit p K k), map_one,
    map_natCast] at h_apply
  have hassoc :
      Associated (ringOfIntegersComplexConj K (((zeta_spec p ℚ K).unit' : 𝓞 K)) - 1)
        (((zeta_spec p ℚ K).unit' : 𝓞 K) - 1) := by
    have h_orig := associated_complexConj_zetaSubOne p K
    change Associated (ringOfIntegersComplexConj K (((zeta_spec p ℚ K).unit' : 𝓞 K)) - 1)
        (((zeta_spec p ℚ K).unit' : 𝓞 K) - 1)
    have h_eq : ringOfIntegersComplexConj K (((zeta_spec p ℚ K).unit' : 𝓞 K)) - 1 =
        ringOfIntegersComplexConj K (zetaSubOne p K) := by
      rw [show (zetaSubOne p K : 𝓞 K) = ((zeta_spec p ℚ K).unit' : 𝓞 K) - 1 from rfl,
        map_sub, map_one]
    rw [h_eq]
    exact h_orig.symm
  exact hassoc.symm.dvd.trans h_apply

/-- The cyclotomic unit `(1 - ζ^k)/(1 - ζ)` is a unit in `𝓞 K` when
`k` is coprime to `p`. -/
theorem isUnit_cyclotomicUnit (k : ℕ) (hk : k.Coprime p) (hp_two : 2 ≤ p) :
    IsUnit (cyclotomicUnit p K k) := by
  unfold cyclotomicUnit
  exact (zeta_spec p ℚ K).unit'_coe.geom_sum_isUnit hp_two hk

/-- The cyclotomic unit packaged as `(𝓞 K)ˣ` when `k` is coprime to `p`. -/
noncomputable def cyclotomicUnitUnit (k : ℕ) (hk : k.Coprime p) (hp_two : 2 ≤ p) :
    (𝓞 K)ˣ :=
  (isUnit_cyclotomicUnit p K k hk hp_two).unit

@[simp]
theorem cyclotomicUnitUnit_val (k : ℕ) (hk : k.Coprime p) (hp_two : 2 ≤ p) :
    (cyclotomicUnitUnit p K k hk hp_two : 𝓞 K) = cyclotomicUnit p K k :=
  IsUnit.unit_spec _

/-- `(ζ - 1) ∣ (ζ^k - 1)` in `𝓞 K` for any natural `k`. -/
theorem zetaSubOne_dvd_zeta_pow_sub_one (k : ℕ) :
    (((zeta_spec p ℚ K).unit' : 𝓞 K) - 1) ∣
      (((zeta_spec p ℚ K).unit' : 𝓞 K) ^ k - 1) :=
  ⟨cyclotomicUnit p K k, (zeta_sub_one_mul_cyclotomicUnit p K k).symm⟩

end CyclotomicUnits
end PrimaryPlus
end LehmerVandiver

end KummerCriterion

end
