module

public import Mathlib.NumberTheory.NumberField.CMField
public import Mathlib.NumberTheory.NumberField.ClassNumber
public import Mathlib.NumberTheory.Cyclotomic.Basic
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Basic
public import Mathlib.NumberTheory.NumberField.Cyclotomic.Embeddings
public import Mathlib.NumberTheory.RamificationInertia.Ramification
public import Mathlib.LinearAlgebra.Dimension.StrongRankCondition
public import Mathlib.RingTheory.Flat.TorsionFree
public import Mathlib.RingTheory.Flat.FaithfullyFlat.Algebra
public import Mathlib.RingTheory.Ideal.GoingUp
public import BernoulliRegular.ClassGroupExtension
public import FltRegular.NumberTheory.RegularPrimes
public import FltRegular.NumberTheory.Cyclotomic.UnitLemmas
import FltRegular.NumberTheory.Cyclotomic.MoreLemmas

/-!
# Basic CM data for the totally real subfield

This file packages the CM-structure, degree formulas, unit-index computation,
and the local class-number notation `h` / `h⁺`.
-/

@[expose] public section

noncomputable section

open NumberField NumberField.IsCMField Algebra IsCyclotomicExtension
open scoped NumberField nonZeroDivisors

namespace BernoulliRegular

section CyclotomicSetup

variable (p : ℕ) [hp : Fact p.Prime] (hp_odd : p ≠ 2)
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- Notation for the maximal totally real subfield of `K`. Scoped to this
section; `K` refers to the ambient variable introduced above. -/
local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-! ### 1. CM structure -/

include hp_odd in
/-- Any `p`-th cyclotomic extension of `ℚ` is a CM field for `p` an odd
prime. -/
theorem isCMField_of_cyclotomic : IsCMField K :=
  Rat.isCMField (S := {p}) _ ⟨p, by grind [hp.1.two_le]⟩

/-! ### 2. Basic dimensions -/

/-- `[K : K⁺] = 2`. -/
theorem finrank_K_over_Kplus [IsCMField K] :
    Module.finrank (K⁺) K = 2 :=
  IsQuadraticExtension.finrank_eq_two _ _

/-- `[K⁺ : ℚ] = (p-1)/2`. -/
theorem finrank_Kplus_over_rat [IsCMField K] :
    Module.finrank ℚ (K⁺) = (p - 1) / 2 := by
  have h1 : Module.finrank (K⁺) K = 2 := finrank_K_over_Kplus K
  have h2 : Module.finrank ℚ K = p - 1 := by
    rw [IsCyclotomicExtension.finrank K (Polynomial.cyclotomic.irreducible_rat hp.1.pos),
        Nat.totient_prime hp.1]
  have htow := Module.finrank_mul_finrank ℚ (K⁺) K
  rw [h1, h2] at htow
  exact (Nat.div_eq_of_eq_mul_left (by omega) htow.symm).symm

/-! ### 3. The unit index `Q` -/

include hp_odd in
/-- **Diekmann Cor 38.** The index of the subgroup generated by the real
units and the roots of unity inside `𝒪_K^×` equals `1` when `K` is a `p`-th
cyclotomic extension of `ℚ` for an odd prime `p`.

This is the `Q = 1` fact used in the class-number-formula split. -/
theorem indexRealUnits_eq_one [IsCMField K] :
    IsCMField.indexRealUnits K = 1 := by
  have hp2 : 2 < p := lt_of_le_of_ne hp.1.two_le (Ne.symm hp_odd)
  have hζ := IsCyclotomicExtension.zeta_spec p ℚ K
  have hzeta_torsion : hζ.unit' ∈ NumberField.Units.torsion K := by
    refine (CommGroup.mem_torsion _ _).2 (isOfFinOrder_iff_pow_eq_one.2 ⟨p, by omega, ?_⟩)
    exact hζ.unit'_pow
  have hrange :
      (IsCMField.unitsMulComplexConjInv K).range =
        (powMonoidHom 2 : NumberField.Units.torsion K →* NumberField.Units.torsion K).range := by
    refine le_antisymm ?_ ?_
    · rintro x ⟨u, rfl⟩
      obtain ⟨m, hm⟩ := unit_inv_conj_is_root_of_unity hζ u hp2
      refine ⟨⟨hζ.unit' ^ m, (NumberField.Units.torsion K).pow_mem hzeta_torsion m⟩, ?_⟩
      apply Subtype.ext
      simpa [pow_two] using hm.symm
    · rintro x ⟨u, rfl⟩
      exact ⟨u, by simp [pow_two]⟩
  have hrange_idx : (IsCMField.unitsMulComplexConjInv K).range.index = 2 := by
    rw [hrange, IsCyclic.index_powMonoidHom_range, Nat.gcd_eq_right]
    rw [Nat.card_eq_fintype_card]
    exact even_iff_two_dvd.mp (NumberField.Units.even_torsionOrder K)
  have hmul : IsCMField.indexRealUnits K * 2 = 2 := by
    simpa [hrange_idx] using IsCMField.indexRealUnits_mul_eq K
  omega

/-! ### 4. Class number definitions -/

/-- The class number of `K`, written locally as `h`. -/
noncomputable def h : ℕ := Fintype.card (ClassGroup (𝓞 K))

/-- The class number of the totally real subfield `K⁺`, written locally as `h⁺`. -/
noncomputable def hPlus [IsCMField K] : ℕ := Fintype.card (ClassGroup (𝓞 (K⁺)))

end CyclotomicSetup

end BernoulliRegular

end
