module

public import KummerCriterion.CyclotomicUnits.DworkParameter.Part8
public import KummerCriterion.CyclotomicUnits.DworkParameter.Part9
import Mathlib.RingTheory.WittVector.IsPoly
import Mathlib.Tactic.NormNum.BigOperators
import Mathlib.Tactic.NormNum.Irrational
import Mathlib.Tactic.NormNum.IsCoprime
import Mathlib.Tactic.NormNum.IsSquare
import Mathlib.Tactic.NormNum.LegendreSymbol
import Mathlib.Tactic.NormNum.ModEq
import Mathlib.Tactic.NormNum.NatFactorial
import Mathlib.Tactic.NormNum.NatFib
import Mathlib.Tactic.NormNum.NatLog
import Mathlib.Tactic.NormNum.NatSqrt
import Mathlib.Tactic.NormNum.Ordinal
import Mathlib.Tactic.NormNum.Parity
import Mathlib.Tactic.NormNum.Prime
import Mathlib.Tactic.NormNum.RealSqrt
import Mathlib.Tactic.ReduceModChar

@[expose] public section

noncomputable section

open scoped NumberField
open PowerSeries

namespace KummerCriterion
namespace CyclotomicUnits
namespace PadicLogSetup
namespace DworkParameter

variable (p : ℕ) [Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

theorem dworkParameter_mul_pow_pred_add_p_mul_tailUnit_eq_zero
    (hp_two : 2 < p) :
    dworkParameter p K *
        (dworkParameter p K ^ (p - 1) +
          (p : DworkCompleteIntegerRing p K) *
            artinHasseTailUnit (p := p) (K := K) hp_two) = 0 := by
  apply AdicCompletion.ext_evalₐ
  intro n
  cases n with
  | zero =>
      exact quotient_pow_zero_eq_zero (p := p) (K := K) (lambdaIdeal p K) _
  | succ N =>
      cases N with
      | zero =>
          rw [map_mul, dworkParameter_evalₐ_one]
          simp
      | succ N =>
          have hfinite :=
            dworkParameterFinite_corrected_factor_eq_zero
              (p := p) (K := K) (N := N + 1) (Nat.succ_pos N)
          rw [map_mul, map_add, map_pow, map_mul, map_natCast,
            dworkParameter_evalₐ, artinHasseTailUnit_evalₐ_succ]
          exact hfinite

theorem dworkParameter_pow_pred_eq_neg_p_mul_tailUnit
    (hp_two : 2 < p) :
    dworkParameter p K ^ (p - 1) =
      -(p : DworkCompleteIntegerRing p K) *
        artinHasseTailUnit (p := p) (K := K) hp_two := by
  have hinside :
      dworkParameter p K ^ (p - 1) +
        (p : DworkCompleteIntegerRing p K) *
          artinHasseTailUnit (p := p) (K := K) hp_two = 0 :=
    dworkParameter_mul_eq_zero (p := p) (K := K)
      (dworkParameter_mul_pow_pred_add_p_mul_tailUnit_eq_zero
        (p := p) (K := K) hp_two)
  simpa [neg_mul] using eq_neg_of_add_eq_zero_left hinside

end DworkParameter
end PadicLogSetup
end CyclotomicUnits
end KummerCriterion

end

@[expose] public section

noncomputable section

open scoped NumberField

namespace KummerCriterion
namespace CyclotomicUnits
namespace PadicLogSetup
namespace DworkParameter

variable (p : ℕ) [Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The principal ideal generated by the corrected Dwork parameter. -/
abbrev dworkParameterIdeal : Ideal (DworkCompleteIntegerRing p K) :=
  Ideal.span ({dworkParameter p K} : Set (DworkCompleteIntegerRing p K))

/-- The corrected Dwork parameter generates the same completed ideal as
`lambda`. This is the completion-side uniformizer statement. -/
theorem dworkParameterIdeal_eq_dworkCompleteLambdaIdeal :
    dworkParameterIdeal p K = dworkCompleteLambdaIdeal p K := by
  rcases dworkParameter_eq_dworkCompleteLambda_mul_unit (p := p) (K := K)
    with ⟨u, hu⟩
  rw [dworkParameterIdeal, hu]
  rw [Ideal.span_singleton_mul_right_unit u.isUnit]
  exact (dworkCompleteLambdaIdeal_eq_span (p := p) (K := K)).symm

theorem dworkCompleteLambdaIdeal_eq_dworkParameterIdeal :
    dworkCompleteLambdaIdeal p K = dworkParameterIdeal p K :=
  (dworkParameterIdeal_eq_dworkCompleteLambdaIdeal (p := p) (K := K)).symm

/-- Exact same-prime ramification transported to the Dwork completion:
`(p) = (lambda)^(p-1)`. -/
theorem span_natCast_prime_dworkComplete_eq_lambdaIdeal_pow_pred :
    Ideal.span ({(p : DworkCompleteIntegerRing p K)} :
        Set (DworkCompleteIntegerRing p K)) =
      (dworkCompleteLambdaIdeal p K) ^ (p - 1) := by
  let R : Type _ := ValuedIntegerRing p K
  let S : Type _ := DworkCompleteIntegerRing p K
  let f : R →+* S := algebraMap R S
  have h := congrArg (fun I : Ideal R => Ideal.map f I)
    (span_natCast_prime_eq_lambdaIdeal_pow_pred (p := p) (K := K))
  change Ideal.map f (Ideal.span ({(p : R)} : Set R)) =
    Ideal.map f ((lambdaIdeal p K) ^ (p - 1)) at h
  rw [Ideal.map_span, Ideal.map_pow] at h
  simpa [S, R, f, dworkCompleteLambdaIdeal, Set.image_singleton] using h

/-- Exact same-prime ramification with the corrected Dwork parameter as
uniformizer: `(p) = (varpi)^(p-1)`. -/
theorem span_natCast_prime_dworkComplete_eq_parameterIdeal_pow_pred :
    Ideal.span ({(p : DworkCompleteIntegerRing p K)} :
        Set (DworkCompleteIntegerRing p K)) =
      (dworkParameterIdeal p K) ^ (p - 1) := by
  rw [span_natCast_prime_dworkComplete_eq_lambdaIdeal_pow_pred (p := p) (K := K),
    dworkParameterIdeal_eq_dworkCompleteLambdaIdeal (p := p) (K := K)]

/-- The Dwork ramification unit `epsilon_varpi` with
`p * epsilon_varpi = varpi^(p - 1)`. -/
noncomputable def dworkRamificationUnit (hp_two : 2 < p) :
    DworkCompleteIntegerRing p K :=
  -artinHasseTailUnit (p := p) (K := K) hp_two

theorem natCast_prime_mul_dworkRamificationUnit
    (hp_two : 2 < p) :
    (p : DworkCompleteIntegerRing p K) *
        dworkRamificationUnit (p := p) (K := K) hp_two =
      dworkParameter p K ^ (p - 1) := by
  rw [dworkRamificationUnit]
  calc
    (p : DworkCompleteIntegerRing p K) *
        -artinHasseTailUnit (p := p) (K := K) hp_two =
      -(p : DworkCompleteIntegerRing p K) *
        artinHasseTailUnit (p := p) (K := K) hp_two := by ring
    _ = dworkParameter p K ^ (p - 1) :=
        (dworkParameter_pow_pred_eq_neg_p_mul_tailUnit
          (p := p) (K := K) hp_two).symm

theorem dworkRamificationUnit_mul_natCast_prime
    (hp_two : 2 < p) :
    dworkRamificationUnit (p := p) (K := K) hp_two *
        (p : DworkCompleteIntegerRing p K) =
      dworkParameter p K ^ (p - 1) := by
  rw [mul_comm, natCast_prime_mul_dworkRamificationUnit
    (p := p) (K := K) hp_two]

/-- The ramification unit is congruent to `-1` to the Artin-Hasse tail
precision. The weaker first-order version is
`dworkRamificationUnit_add_one_mem_dworkParameterIdeal`; this strengthened
form is what makes the folded `p`-term purely linear modulo
`varpi^(p - 1)`. -/
theorem dworkRamificationUnit_add_one_mem_dworkParameterIdeal_pow_tail
    (hp_two : 2 < p) :
    dworkRamificationUnit (p := p) (K := K) hp_two + 1 ∈
      (dworkParameterIdeal p K) ^ ((p - 1) ^ 2) := by
  have htail :
      artinHasseTail (p := p) (K := K) hp_two ∈
        (dworkParameterIdeal p K) ^ ((p - 1) ^ 2) := by
    simpa [dworkParameterIdeal_eq_dworkCompleteLambdaIdeal (p := p) (K := K)]
      using artinHasseTail_mem_dworkCompleteLambdaIdeal_pow
        (p := p) (K := K) hp_two
  have hneg :
      -artinHasseTail (p := p) (K := K) hp_two ∈
        (dworkParameterIdeal p K) ^ ((p - 1) ^ 2) :=
    ((dworkParameterIdeal p K) ^ ((p - 1) ^ 2)).neg_mem htail
  convert hneg using 1
  rw [dworkRamificationUnit,
    artinHasseTailUnit_eq_one_add_artinHasseTail (p := p) (K := K) hp_two]
  ring

/-- Integral form of the folded same-prime `p`-term. -/
theorem natCast_prime_mul_dworkRamificationCorrection
    (hp_two : 2 < p) (Z : DworkCompleteIntegerRing p K) :
    (p : DworkCompleteIntegerRing p K) *
        (dworkRamificationUnit (p := p) (K := K) hp_two *
          dworkParameter p K * Z ^ p) =
      (dworkParameter p K * Z) ^ p := by
  let S : Type _ := DworkCompleteIntegerRing p K
  let varpi : S := dworkParameter p K
  let eps : S := dworkRamificationUnit (p := p) (K := K) hp_two
  have hram : (p : S) * eps = varpi ^ (p - 1) := by
    simpa [S, varpi, eps] using
      natCast_prime_mul_dworkRamificationUnit (p := p) (K := K) hp_two
  have hpow : varpi ^ (p - 1) * varpi = varpi ^ p := by
    rw [← pow_succ, Nat.sub_one_add_one]
    exact Nat.ne_of_gt (Fact.out : Nat.Prime p).pos
  calc
    (p : S) * (eps * varpi * Z ^ p) =
        ((p : S) * eps) * varpi * Z ^ p := by ring
    _ = varpi ^ (p - 1) * varpi * Z ^ p := by rw [hram]
    _ = varpi ^ p * Z ^ p := by rw [hpow]
    _ = (varpi * Z) ^ p := by rw [mul_pow]

theorem natCast_prime_mul_dworkRamificationCorrection_of_eq
    (hp_two : 2 < p) {Y Z : DworkCompleteIntegerRing p K}
    (hY : Y = dworkParameter p K * Z) :
    (p : DworkCompleteIntegerRing p K) *
        (dworkRamificationUnit (p := p) (K := K) hp_two *
          dworkParameter p K * Z ^ p) =
      Y ^ p := by
  rw [hY]
  exact natCast_prime_mul_dworkRamificationCorrection
    (p := p) (K := K) hp_two Z

omit [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K] in
/-- Frobenius congruence modulo the ramified prime-power ideal. If two
elements are congruent modulo `I`, then their `p`-th powers are congruent
modulo `I^(p - 1)` as soon as `p ∈ I^(p - 1)`. -/
theorem pow_prime_sub_pow_mem_ideal_pow_pred_of_sub_mem {R : Type*} [CommRing R]
    (I : Ideal R) (hpI : (p : R) ∈ I ^ (p - 1))
    {x y : R} (hxy : x - y ∈ I) :
    x ^ p - y ^ p ∈ I ^ (p - 1) := by
  let J : Ideal R := I ^ (p - 1)
  let q : R →+* R ⧸ J := Ideal.Quotient.mk J
  rw [← Ideal.Quotient.eq_zero_iff_mem]
  change q (x ^ p - y ^ p) = 0
  rw [map_sub, map_pow, map_pow]
  let d : R := x - y
  have hx_eq : x = d + y := by
    simp [d]
  have hq_eq : q x = q d + q y := by
    rw [hx_eq, map_add]
  have hp_zero : ((p : ℕ) : R ⧸ J) = 0 := by
    change q (p : R) = 0
    exact Ideal.Quotient.eq_zero_iff_mem.mpr hpI
  rw [hq_eq, add_pow]
  rw [Finset.sum_eq_single 0]
  · simp
  · intro m hm hm0
    have hm_lt_succ : m < p + 1 := Finset.mem_range.mp hm
    by_cases hmp : m = p
    · subst m
      have hd_pow : d ^ p ∈ I ^ p := Ideal.pow_mem_pow (by simpa [d] using hxy) p
      have hd_zero : (q d) ^ p = 0 := by
        rw [← map_pow]
        exact Ideal.Quotient.eq_zero_iff_mem.mpr
          (Ideal.pow_le_pow_right (by omega : p - 1 ≤ p) hd_pow)
      simp [hd_zero]
    · have hm_lt : m < p := by omega
      have hchoose_dvd : p ∣ p.choose m :=
        Nat.Prime.dvd_choose_self (Fact.out : Nat.Prime p) hm0 hm_lt
      rcases hchoose_dvd with ⟨t, ht⟩
      have hcoeff_zero : ((p.choose m : ℕ) : R ⧸ J) = 0 := by
        rw [ht, Nat.cast_mul, hp_zero, zero_mul]
      simp [hcoeff_zero]
  · intro hnot
    exact False.elim (hnot (Finset.mem_range.mpr (Nat.succ_pos p)))

theorem dwork_pow_prime_sub_pow_mem_parameterIdeal_pow_pred_of_sub_mem
    {x y : DworkCompleteIntegerRing p K}
    (hxy : x - y ∈ dworkParameterIdeal p K) :
    x ^ p - y ^ p ∈ (dworkParameterIdeal p K) ^ (p - 1) := by
  have hpI :
      (p : DworkCompleteIntegerRing p K) ∈
        (dworkParameterIdeal p K) ^ (p - 1) := by
    change (p : DworkCompleteIntegerRing p K) ∈ (dworkParameterIdeal p K) ^ (p - 1)
    rw [← span_natCast_prime_dworkComplete_eq_parameterIdeal_pow_pred
      (p := p) (K := K)]
    exact Ideal.mem_span_singleton_self (p : DworkCompleteIntegerRing p K)
  exact pow_prime_sub_pow_mem_ideal_pow_pred_of_sub_mem
    (p := p) (I := dworkParameterIdeal p K) hpI hxy

/-- At the Kummer precision, the folded same-prime correction is purely
linear: replacing `Z` by its residue `z0` leaves
`epsilon_varpi * varpi * Z^p` congruent to `-z0^p * varpi` modulo
`varpi^(p - 1)`. -/
theorem dworkRamificationCorrection_sub_linear_mem_parameterIdeal_pow_pred
    (hp_two : 2 < p) {Z z0 : DworkCompleteIntegerRing p K}
    (hZ : Z - z0 ∈ dworkParameterIdeal p K) :
    dworkRamificationUnit (p := p) (K := K) hp_two *
          dworkParameter p K * Z ^ p -
        (-(z0 ^ p) * dworkParameter p K) ∈
      (dworkParameterIdeal p K) ^ (p - 1) := by
  let S : Type _ := DworkCompleteIntegerRing p K
  let I : Ideal S := dworkParameterIdeal p K
  let varpi : S := dworkParameter p K
  let eps : S := dworkRamificationUnit (p := p) (K := K) hp_two
  change eps * varpi * Z ^ p - (-(z0 ^ p) * varpi) ∈ I ^ (p - 1)
  have hvarpi : varpi ∈ I := by
    change dworkParameter p K ∈ dworkParameterIdeal p K
    rw [dworkParameterIdeal]
    exact Ideal.mem_span_singleton_self (dworkParameter p K)
  have heps_high : eps + 1 ∈ I ^ ((p - 1) ^ 2) := by
    simpa [eps, I] using
      dworkRamificationUnit_add_one_mem_dworkParameterIdeal_pow_tail
        (p := p) (K := K) hp_two
  have hpow :
      Z ^ p - z0 ^ p ∈ I ^ (p - 1) :=
    dwork_pow_prime_sub_pow_mem_parameterIdeal_pow_pred_of_sub_mem
      (p := p) (K := K) hZ
  have hleft :
      varpi * (eps * (Z ^ p - z0 ^ p)) ∈ I ^ (p - 1) := by
    have hprod : varpi * (eps * (Z ^ p - z0 ^ p)) ∈ I * I ^ (p - 1) :=
      Ideal.mul_mem_mul hvarpi (Ideal.mul_mem_left _ _ hpow)
    have hprod' :
        varpi * (eps * (Z ^ p - z0 ^ p)) ∈ I ^ ((p - 1) + 1) := by
      simpa [pow_succ'] using hprod
    exact Ideal.pow_le_pow_right (by omega : p - 1 ≤ p - 1 + 1) hprod'
  have hright :
      varpi * ((eps + 1) * z0 ^ p) ∈ I ^ (p - 1) := by
    have hinner : (eps + 1) * z0 ^ p ∈ I ^ ((p - 1) ^ 2) :=
      (I ^ ((p - 1) ^ 2)).mul_mem_right (z0 ^ p) heps_high
    have hprod :
        varpi * ((eps + 1) * z0 ^ p) ∈ I * I ^ ((p - 1) ^ 2) :=
      Ideal.mul_mem_mul hvarpi hinner
    have hprod' :
        varpi * ((eps + 1) * z0 ^ p) ∈ I ^ (((p - 1) ^ 2) + 1) := by
      simpa [pow_succ'] using hprod
    exact Ideal.pow_le_pow_right (by
      have hp_pred_pos : 0 < p - 1 := by omega
      nlinarith [sq_nonneg (p - 1 : ℤ)]
    ) hprod'
  have hsum :
      varpi * (eps * (Z ^ p - z0 ^ p)) +
        varpi * ((eps + 1) * z0 ^ p) ∈ I ^ (p - 1) :=
    (I ^ (p - 1)).add_mem hleft hright
  convert hsum using 1
  ring

/-- Multiplication by the corrected Dwork parameter is injective on the Dwork
completion. -/
theorem dworkParameter_regular :
    ∀ {x : DworkCompleteIntegerRing p K}, dworkParameter p K * x = 0 → x = 0 :=
  fun hx => dworkParameter_mul_eq_zero (p := p) (K := K) hx

theorem dworkParameter_pow_regular (n : ℕ)
    {x : DworkCompleteIntegerRing p K}
    (hx : dworkParameter p K ^ n * x = 0) :
    x = 0 := by
  induction n with
  | zero =>
      simpa using hx
  | succ n ih =>
      have hmul :
          dworkParameter p K * (dworkParameter p K ^ n * x) = 0 := by
        simpa [pow_succ, pow_succ', mul_comm, mul_left_comm, mul_assoc] using hx
      have hn : dworkParameter p K ^ n * x = 0 :=
        dworkParameter_regular (p := p) (K := K) hmul
      exact ih hn

/-- Multiplication by `p` is injective in the complete Dwork ring. -/
theorem natCast_prime_dworkComplete_regular
    (hp_two : 2 < p) {x : DworkCompleteIntegerRing p K}
    (hx : (p : DworkCompleteIntegerRing p K) * x = 0) :
    x = 0 := by
  let S : Type _ := DworkCompleteIntegerRing p K
  let varpi : S := dworkParameter p K
  let eps : S := dworkRamificationUnit (p := p) (K := K) hp_two
  have hram : eps * (p : S) = varpi ^ (p - 1) := by
    simpa [S, varpi, eps] using
      dworkRamificationUnit_mul_natCast_prime (p := p) (K := K) hp_two
  have hpow : varpi ^ (p - 1) * x = 0 := by
    calc
      varpi ^ (p - 1) * x = (eps * (p : S)) * x := by rw [← hram]
      _ = eps * ((p : S) * x) := by ring
      _ = 0 := by rw [hx, mul_zero]
  exact dworkParameter_pow_regular (p := p) (K := K) (p - 1) hpow

end DworkParameter
end PadicLogSetup
end CyclotomicUnits
end KummerCriterion

end
