import BernoulliRegular.CyclotomicUnits.Subgroup
import BernoulliRegular.FLT37.LehmerVandiver.PlusCoprime.Sinnott.LogEmbedding
import BernoulliRegular.FLT37.LehmerVandiver.PlusCoprime.Sinnott.IndexFormula

/-!
# P-primary cyclotomic-unit index formula

This file records the p-primary form of Sinnott's cyclotomic-unit index formula
for the real prime-conductor cyclotomic-unit family. The hard analytic input is
kept explicit as `FLT37.Sinnott.KummerDirichletDeterminant`.
-/

@[expose] public section

noncomputable section

open NumberField

namespace BernoulliRegular

variable {p : ℕ} [Fact p.Prime]
variable {K : Type} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-- The full-rank real cyclotomic-unit subgroup used by the existing Sinnott
regulator/index infrastructure: the family generated by the squared real
cyclotomic units, together with torsion in `K⁺`. -/
def cyclotomicUnitIndexSubgroup (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    Subgroup (𝓞 K⁺)ˣ :=
  Subgroup.closure
      (Set.range (FLT37.Sinnott.cyclotomicUnitFamilyKplusFinRank p K hp_odd hp_three)) ⊔
    NumberField.Units.torsion K⁺

theorem prime_not_dvd_two_pow (hp_odd : p ≠ 2) (r : ℕ) : ¬ p ∣ 2 ^ r := by
  intro hp_dvd
  have hp_dvd_two : p ∣ 2 := (Fact.out : Nat.Prime p).dvd_of_dvd_pow hp_dvd
  exact prime_not_dvd_sign_factor (p := p) hp_odd hp_dvd_two

/-- The harmless `2^r` factor in the squared-family normalization has no
effect on p-primary divisibility for odd `p`. -/
theorem prime_dvd_two_pow_mul_iff_dvd (hp_odd : p ≠ 2) (r n : ℕ) :
    p ∣ 2 ^ r * n ↔ p ∣ n := by
  constructor
  · intro h
    rcases (Fact.out : Nat.Prime p).dvd_mul.mp h with hpow | hn
    · exact (prime_not_dvd_two_pow (p := p) hp_odd r hpow).elim
    · exact hn
  · exact fun hn => dvd_mul_of_dvd_right hn (2 ^ r)

/-- P-primary form of the real cyclotomic-unit index formula, conditional on
the existing explicit Sinnott index formula. -/
theorem cyclotomicUnitIndex_primeConductor_pPrimary_of_sinnottIndexFormula
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (hSinnott : FLT37.Sinnott.SinnottIndexFormula p K hp_odd hp_three) :
    p ∣ (cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three).index ↔
      p ∣ hPlus K := by
  have hindex := FLT37.Sinnott.index_eq_twoPow_mul_hPlus_of_sinnottIndexFormula
    p K hp_odd hp_three hSinnott
  change (cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three).index =
      2 ^ ((p - 3) / 2) * hPlus K at hindex
  rw [hindex]
  exact prime_dvd_two_pow_mul_iff_dvd (p := p) hp_odd ((p - 3) / 2) (hPlus K)

/-- P-primary cyclotomic-unit index formula from the named hard analytic input
`KummerDirichletDeterminant`.

The determinant input gives the squared-family index
`2^((p - 3) / 2) * hPlus K`; the final equivalence removes the power of `2`
using `p ≠ 2`. -/
theorem cyclotomicUnitIndex_primeConductor_pPrimary_of_kummerDirichletDeterminant
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (hdet : FLT37.Sinnott.KummerDirichletDeterminant p K hp_odd hp_three) :
    p ∣ (cyclotomicUnitIndexSubgroup (p := p) (K := K) hp_odd hp_three).index ↔
      p ∣ hPlus K := by
  have hreg : FLT37.Sinnott.SinnottRegulatorIdentity p K hp_odd hp_three :=
    (FLT37.Sinnott.sinnottRegulatorIdentity_iff_kummerDirichletDeterminant
      (p := p) (K := K) hp_odd hp_three).1 hdet
  have hSinnott : FLT37.Sinnott.SinnottIndexFormula p K hp_odd hp_three :=
    FLT37.Sinnott.sinnottIndexFormula_of_regulatorIdentity
      p K hp_odd hp_three hreg
  exact cyclotomicUnitIndex_primeConductor_pPrimary_of_sinnottIndexFormula
    (p := p) (K := K) hp_odd hp_three hSinnott

end BernoulliRegular

end
