import BernoulliRegular.CyclotomicUnits.NormalizedUnits
import BernoulliRegular.CyclotomicUnits.Subgroup
import BernoulliRegular.CyclotomicUnits.IndexComparison
import Mathlib.GroupTheory.Schreier

/-!
# The normalized real cyclotomic-unit subgroup

This file defines the TeX subgroup generated by `-1` and the normalized real
cyclotomic units `ε_a`, for `2 ≤ a ≤ (p - 1) / 2`.  It is intentionally named
`normalizedCPlus` while the older squared-family subgroup is still present
under the route-level name `CPlus`.
-/

@[expose] public section

noncomputable section

open NumberField

namespace BernoulliRegular

variable {p : ℕ} [Fact p.Prime]
variable {K : Type*} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
  [NumberField.IsCMField K]

local notation3 "K⁺" => NumberField.maximalRealSubfield K

/-- The normalized real cyclotomic-unit generator indexed by
`i : Fin ((p - 3) / 2)`, corresponding to `a = i + 2`. -/
noncomputable def normalizedCPlusGenerator (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (i : Fin ((p - 3) / 2)) : (𝓞 K⁺)ˣ :=
  normalizedCyclotomicUnitPlusUnit (p := p) (K := K) hp_odd
    (CPlusGeneratorIndex (p := p) hp_three i)
    (CPlusGeneratorIndex_two_le (p := p) hp_three i)
    (CPlusGeneratorIndex_le_half (p := p) hp_three i)

/-- The TeX normalized subgroup
`C⁺ = <-1, ε₂, ..., ε_g> ≤ (𝓞 K⁺)ˣ`. -/
def normalizedCPlus (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) : Subgroup (𝓞 K⁺)ˣ :=
  Subgroup.closure
    ({(-1 : (𝓞 K⁺)ˣ)} ∪
      Set.range (normalizedCPlusGenerator (p := p) (K := K) hp_odd hp_three))

theorem neg_one_mem_normalizedCPlus (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    (-1 : (𝓞 K⁺)ˣ) ∈ normalizedCPlus (p := p) (K := K) hp_odd hp_three :=
  Subgroup.subset_closure (by left; rfl)

theorem normalizedCPlusGenerator_mem (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (i : Fin ((p - 3) / 2)) :
    normalizedCPlusGenerator (p := p) (K := K) hp_odd hp_three i ∈
      normalizedCPlus (p := p) (K := K) hp_odd hp_three :=
  Subgroup.subset_closure (by right; exact ⟨i, rfl⟩)

theorem normalizedCPlusGenerator_sq_eq_CPlusGenerator
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (i : Fin ((p - 3) / 2)) :
    normalizedCPlusGenerator (p := p) (K := K) hp_odd hp_three i ^ 2 =
      CPlusGenerator (p := p) (K := K) hp_three i := by
  unfold normalizedCPlusGenerator CPlusGenerator
  exact normalizedCyclotomicUnitPlusUnit_sq_eq_realCyclotomicUnit
    (p := p) (K := K) hp_odd
    (CPlusGeneratorIndex (p := p) hp_three i)
    (CPlusGeneratorIndex_two_le (p := p) hp_three i)
    (CPlusGeneratorIndex_le_half (p := p) hp_three i)

theorem normalizedCPlusGenerator_sq_mem_CPlus
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (i : Fin ((p - 3) / 2)) :
    normalizedCPlusGenerator (p := p) (K := K) hp_odd hp_three i ^ 2 ∈
      CPlus (p := p) (K := K) hp_three := by
  rw [normalizedCPlusGenerator_sq_eq_CPlusGenerator
    (p := p) (K := K) hp_odd hp_three i]
  exact CPlusGenerator_mem (p := p) (K := K) hp_three i

/-- The older squared-family subgroup is contained in the normalized TeX
subgroup. -/
theorem CPlus_le_normalizedCPlus (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    CPlus (p := p) (K := K) hp_three ≤
      normalizedCPlus (p := p) (K := K) hp_odd hp_three := by
  unfold CPlus
  rw [Subgroup.closure_le]
  rintro x (hx | hx)
  · rcases hx with rfl
    exact neg_one_mem_normalizedCPlus (p := p) (K := K) hp_odd hp_three
  · rcases hx with ⟨i, rfl⟩
    rw [← normalizedCPlusGenerator_sq_eq_CPlusGenerator
      (p := p) (K := K) hp_odd hp_three i]
    exact Subgroup.pow_mem _
      (normalizedCPlusGenerator_mem (p := p) (K := K) hp_odd hp_three i) 2

instance normalizedCPlus_fg (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    Group.FG (normalizedCPlus (p := p) (K := K) hp_odd hp_three) := by
  unfold normalizedCPlus
  infer_instance

theorem normalizedCPlus_sq_mem_CPlus (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    {x : (𝓞 K⁺)ˣ}
    (hx : x ∈ normalizedCPlus (p := p) (K := K) hp_odd hp_three) :
    x ^ 2 ∈ CPlus (p := p) (K := K) hp_three := by
  unfold normalizedCPlus at hx
  induction hx using Subgroup.closure_induction with
  | mem x hx =>
      rcases hx with hx | hx
      · rcases hx with rfl
        simp
      · rcases hx with ⟨i, rfl⟩
        exact normalizedCPlusGenerator_sq_mem_CPlus
          (p := p) (K := K) hp_odd hp_three i
  | one =>
      simp
  | mul x y _ _ hx hy =>
      simpa [pow_two, mul_assoc, mul_left_comm, mul_comm] using
        (CPlus (p := p) (K := K) hp_three).mul_mem hx hy
  | inv x _ hx =>
      simpa [pow_two] using
        (CPlus (p := p) (K := K) hp_three).inv_mem hx

theorem normalizedCPlus_quotient_pow_two_eq_one (hp_odd : p ≠ 2) (hp_three : 3 ≤ p)
    (x :
      normalizedCPlus (p := p) (K := K) hp_odd hp_three ⧸
        (CPlus (p := p) (K := K) hp_three).subgroupOf
          (normalizedCPlus (p := p) (K := K) hp_odd hp_three)) :
    x ^ 2 = 1 := by
  refine Quotient.inductionOn' x ?_
  intro x
  rw [← QuotientGroup.mk_pow, QuotientGroup.eq_one_iff]
  rw [Subgroup.mem_subgroupOf]
  simpa using
    normalizedCPlus_sq_mem_CPlus (p := p) (K := K) hp_odd hp_three x.property

theorem CPlus_relIndex_normalizedCPlus_dvd_two_pow (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    (CPlus (p := p) (K := K) hp_three).relIndex
        (normalizedCPlus (p := p) (K := K) hp_odd hp_three) ∣
      2 ^ Group.rank
        (normalizedCPlus (p := p) (K := K) hp_odd hp_three ⧸
          (CPlus (p := p) (K := K) hp_three).subgroupOf
            (normalizedCPlus (p := p) (K := K) hp_odd hp_three)) := by
  simpa [Subgroup.relIndex, Subgroup.index] using
    (card_dvd_exponent_pow_rank'
      (normalizedCPlus (p := p) (K := K) hp_odd hp_three ⧸
        (CPlus (p := p) (K := K) hp_three).subgroupOf
          (normalizedCPlus (p := p) (K := K) hp_odd hp_three))
      (n := 2)
      (normalizedCPlus_quotient_pow_two_eq_one
        (p := p) (K := K) hp_odd hp_three))

theorem CPlus_index_prime_dvd_iff_normalizedCPlus_index_prime_dvd
    (hp_odd : p ≠ 2) (hp_three : 3 ≤ p) :
    p ∣ (CPlus (p := p) (K := K) hp_three).index ↔
      p ∣ (normalizedCPlus (p := p) (K := K) hp_odd hp_three).index :=
  subgroup_index_prime_dvd_iff_of_relIndex_dvd_two_pow
    (CPlus_le_normalizedCPlus (p := p) (K := K) hp_odd hp_three)
    (Fact.out : Nat.Prime p) hp_odd
    (CPlus_relIndex_normalizedCPlus_dvd_two_pow
      (p := p) (K := K) hp_odd hp_three)

end BernoulliRegular

end
