module

public import KummerCriterion.UnitQuotient.DeltaAction
public import Mathlib.NumberTheory.NumberField.InfinitePlace.Ramification
public import Mathlib.Algebra.MonoidAlgebra.Module
public import Mathlib.GroupTheory.QuotientGroup.Finite
public import Mathlib.LinearAlgebra.Finsupp.Pi

/-!
# Unit quotients: the even permutation representation

This file proves `REF-07c3`.

The finite representation-theory statement needed for the free unit part is:
the permutation representation of

```text
Delta / {±1}
```

is the regular representation of this quotient, so over a splitting
coefficient ring it decomposes with one copy of every quotient character.
Equivalently, on `Delta` itself, the plus idempotent for complex conjugation
is the sum of the even character idempotents; after subtracting the trivial
idempotent, only the nontrivial even characters remain.
-/

@[expose] public section

noncomputable section

namespace KummerCriterion

open Finset MonoidAlgebra

set_option linter.unusedSectionVars false
set_option linter.unusedDecidableInType false

attribute [local instance] Fintype.ofFinite

variable (p : ℕ) [Fact p.Prime]

/-- The subgroup `{±1}` of `Delta = (ZMod p)^*`, generated by complex
conjugation. -/
abbrev CyclotomicEvenDeltaSubgroup : Subgroup (CyclotomicUnitDelta p) :=
  Subgroup.zpowers (-1 : CyclotomicUnitDelta p)

/-- The quotient `Delta / {±1}` indexing the real embeddings of `Q(zeta_p)^+`. -/
abbrev CyclotomicEvenDelta : Type :=
  CyclotomicUnitDelta p ⧸ CyclotomicEvenDeltaSubgroup p

/-- The quotient map `Delta -> Delta / {±1}`. -/
def cyclotomicEvenDeltaQuotient : CyclotomicUnitDelta p →* CyclotomicEvenDelta p :=
  QuotientGroup.mk' (CyclotomicEvenDeltaSubgroup p)

@[simp]
theorem cyclotomicEvenDeltaQuotient_apply (a : CyclotomicUnitDelta p) :
    cyclotomicEvenDeltaQuotient p a = QuotientGroup.mk a :=
  rfl

@[simp]
theorem cyclotomicEvenDeltaQuotient_neg_one :
    cyclotomicEvenDeltaQuotient p (-1 : CyclotomicUnitDelta p) = 1 :=
  (QuotientGroup.eq_one_iff (-1 : CyclotomicUnitDelta p)).2 (Subgroup.mem_zpowers _)

/-- **Negation invariance of the quotient map**: for any `a : (ZMod p)ˣ`,
`q(-a) = q(a)` in `(ZMod p)ˣ / ⟨-1⟩`. Direct consequence of
`q(-1) = 1` + the homomorphism property `q(-a) = q((-1) · a) = q(-1) · q(a)`. -/
@[simp]
theorem cyclotomicEvenDeltaQuotient_neg (a : CyclotomicUnitDelta p) :
    cyclotomicEvenDeltaQuotient p (-a) = cyclotomicEvenDeltaQuotient p a := by
  have h : -a = (-1 : CyclotomicUnitDelta p) * a := (neg_one_mul a).symm
  rw [h, map_mul, cyclotomicEvenDeltaQuotient_neg_one, one_mul]

/-- **Even function descent**: any function `f : (ZMod p)ˣ → R` satisfying
`f(-a) = f(a)` (= even under negation) descends to a function on the quotient
`(ZMod p)ˣ ⧸ ⟨-1⟩ = CyclotomicEvenDelta p`. This is the function-level analog
of the character-level `evenDeltaCharacterDescend`.

The well-definedness uses `(-1)^k ∈ {1, -1}` for any `k : ℤ` (which follows
from `(-1)^2 = 1` + `zpow_eq_zpow_emod'`). For `k % 2 = 0`, the equivalence
gives `b = a`; for `k % 2 = 1`, it gives `b = -a`, and `hf_even` resolves
the function value. -/
def evenFunctionDescend {R : Type*} (f : CyclotomicUnitDelta p → R)
    (hf_even : ∀ a : CyclotomicUnitDelta p, f (-a) = f a) :
    CyclotomicEvenDelta p → R :=
  fun q => q.liftOn f (fun a b hab => by
    have hab' : a⁻¹ * b ∈ CyclotomicEvenDeltaSubgroup p :=
      QuotientGroup.leftRel_apply.mp hab
    rw [CyclotomicEvenDeltaSubgroup, Subgroup.mem_zpowers_iff] at hab'
    obtain ⟨k, hk⟩ := hab'
    -- hk : (-1)^k = a⁻¹ * b, so b = a * (-1)^k
    have h_b : b = a * ((-1 : CyclotomicUnitDelta p) ^ k) := by
      rw [hk]; group
    -- Use that (-1)^2 = 1 to reduce k mod 2.
    have h_sq : ((-1 : CyclotomicUnitDelta p) ^ (2 : ℕ)) = 1 := by
      rw [sq, neg_one_mul, neg_neg]
    rw [zpow_eq_zpow_emod' k h_sq] at h_b
    -- k % 2 ∈ {0, 1}
    have h_mod : k % ((2 : ℕ) : ℤ) = 0 ∨ k % ((2 : ℕ) : ℤ) = 1 := by omega
    rcases h_mod with h0 | h1
    · rw [h0, zpow_zero, mul_one] at h_b
      rw [h_b]
    · rw [h1, zpow_one] at h_b
      rw [h_b, mul_neg_one, hf_even])

@[simp]
theorem evenFunctionDescend_apply_mk {R : Type*} (f : CyclotomicUnitDelta p → R)
    (hf_even : ∀ a : CyclotomicUnitDelta p, f (-a) = f a)
    (a : CyclotomicUnitDelta p) :
    evenFunctionDescend (p := p) f hf_even
        ((QuotientGroup.mk a) : CyclotomicEvenDelta p) = f a := by
  rfl

/-- Pull a character of `Delta / {±1}` back to an even character of `Delta`. -/
def evenDeltaCharacterPullback {R : Type*} [CommMonoidWithZero R]
    (χ : MulChar (CyclotomicEvenDelta p) R) :
    MulChar (CyclotomicUnitDelta p) R where
  toFun a := χ (cyclotomicEvenDeltaQuotient p a)
  map_one' := by simp [cyclotomicEvenDeltaQuotient]
  map_mul' a b := by simp [cyclotomicEvenDeltaQuotient, map_mul]
  map_nonunit' a ha := (ha (Group.isUnit a)).elim

end KummerCriterion

end
