module

public import BernoulliRegular.UnitQuotient.DeltaAction
public import FltRegular.NumberTheory.Cyclotomic.UnitLemmas

/-!
# Unit quotients: the cyclotomic torsion image

This file proves the torsion part of `REF-07b`: after passing from
`E = O_K^*` to `E/E^p`, the image of the roots of unity is generated by the
distinguished primitive `p`-th root of unity `zeta_p`.

The mathematical point is simple.  In the `p`-th cyclotomic field, every root
of unity is of the form `(-1)^k zeta_p^m`.  Since `p` is odd, `-1 = (-1)^p`,
so the `-1` factor dies in `E/E^p`.
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField

namespace BernoulliRegular

set_option linter.unusedSectionVars false

variable (p : ℕ) [hp : Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

end BernoulliRegular

end
