module

public import BernoulliRegular.UnitQuotient.TorsionQuotient

/-!
# Unit quotients: the character of the cyclotomic torsion line

This file proves the second half of `REF-07b`.  The torsion image in `E/E^p`
was already identified with the cyclic subgroup generated by the class of
`zeta_p`; here we prove that the actual `Delta = (ZMod p)^*` action on that
generator is the Teichmuller action:

```text
sigma_a([zeta_p]) = [zeta_p]^a.
```

Thus the torsion line is the `j = 1` line.  Later component files can use this
with their chosen idempotent/eigenspace API to exclude this torsion line from
the even components `2 <= j <= p - 3`.
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField

namespace BernoulliRegular

set_option linter.unusedSectionVars false

variable (p : ℕ) [hp : Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

end BernoulliRegular

end
