module

public import BernoulliRegular.UnitQuotient.DeltaAction
public import FltRegular.NumberTheory.Cyclotomic.UnitLemmas

/-!
# Unit quotients: the cyclotomic torsion image

This file proves the torsion part of `REF-07b`: after passing from
`E = O_K^*` to `E/E^p`, the image of the roots of unity is generated by the
distinguished primitive `p`-th root of unity `zeta_p`.

The mathematical point is simple.  In the `p`-th cyclotomic field, every root
of unity is of the form `(-1)^k zeta_p^m`.  Since `p` is odd, `-1 = (-1)^p`,
so the `-1` factor dies in `E/E^p`.
-/

@[expose] public section

noncomputable section

open NumberField IsCyclotomicExtension
open scoped NumberField

namespace BernoulliRegular

set_option linter.unusedSectionVars false

variable (p : ℕ) [hp : Fact p.Prime]
variable (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The distinguished primitive `p`-th root of unity, as a global unit. -/
noncomputable abbrev cyclotomicZetaUnit : CyclotomicUnitGroup K :=
  (IsCyclotomicExtension.zeta_spec p ℚ K).unit'

/-- The distinguished primitive root of unity is a torsion unit. -/
theorem cyclotomicZetaUnit_mem_torsion :
    cyclotomicZetaUnit (p := p) K ∈ CyclotomicUnitTorsion K := by
  refine (CommGroup.mem_torsion _ _).2 (isOfFinOrder_iff_pow_eq_one.2 ⟨p, hp.1.pos, ?_⟩)
  simpa [cyclotomicZetaUnit] using
    (IsCyclotomicExtension.zeta_spec p ℚ K).unit'_pow

/-- Every torsion unit in the `p`-th cyclotomic field is `(-1)^k zeta_p^m`. -/
theorem cyclotomic_torsion_unit_eq_neg_one_pow_mul_zeta_pow
    (hp_odd : p ≠ 2) (u : CyclotomicUnitTorsion K) :
    ∃ m k : ℕ,
      (u : CyclotomicUnitGroup K) =
        (-1 : CyclotomicUnitGroup K) ^ k * cyclotomicZetaUnit (p := p) K ^ m := by
  have hpo : Odd p := hp.1.odd_of_ne_two hp_odd
  have hu_fin_order : IsOfFinOrder (u : CyclotomicUnitGroup K) :=
    (CommGroup.mem_torsion _ _).1 u.2
  obtain ⟨n, hn_pos, hu_pow⟩ := isOfFinOrder_iff_pow_eq_one.1 hu_fin_order
  have hu_fin_field :
      ∃ (n : ℕ) (_ : 0 < n), ((u : CyclotomicUnitGroup K) : K) ^ n = 1 := by
    refine ⟨n, hn_pos, ?_⟩
    simpa using congrArg (fun x : CyclotomicUnitGroup K => (x : K)) hu_pow
  obtain ⟨m, k, huk⟩ :=
    roots_of_unity_in_cyclo
      (K := K) (hζ := IsCyclotomicExtension.zeta_spec p ℚ K)
      hpo ((u : CyclotomicUnitGroup K) : K) hu_fin_field
  refine ⟨m, k, ?_⟩
  apply Units.ext
  apply RingOfIntegers.ext
  simpa [cyclotomicZetaUnit, Units.val_mul, Units.val_pow_eq_pow_val] using huk

/-- Since `p` is odd, the class of `-1` is trivial in `E/E^p`. -/
theorem cyclotomicUnitPowerClass_neg_one_eq_one (hp_odd : p ≠ 2) :
    cyclotomicUnitPowerClass (p := p) (N := 1) K (-1 : CyclotomicUnitGroup K) = 1 := by
  have hpo : Odd p := hp.1.odd_of_ne_two hp_odd
  have hpow : (-1 : CyclotomicUnitGroup K) ^ p = -1 := by
    simpa using (Odd.neg_one_pow hpo : (-1 : CyclotomicUnitGroup K) ^ p = -1)
  have hclass :=
    cyclotomicUnitPowerClass_pow_eq_one (p := p) (N := 1) K
      (-1 : CyclotomicUnitGroup K)
  simpa [pow_one, hpow] using hclass

/-- Every power of `-1` has trivial class in `E/E^p`. -/
theorem cyclotomicUnitPowerClass_neg_one_pow_eq_one
    (hp_odd : p ≠ 2) (k : ℕ) :
    cyclotomicUnitPowerClass (p := p) (N := 1) K
        ((-1 : CyclotomicUnitGroup K) ^ k) = 1 := by
  rw [map_pow, cyclotomicUnitPowerClass_neg_one_eq_one (p := p) (K := K) hp_odd, one_pow]

/-- Each torsion unit has the same class in `E/E^p` as a power of `zeta_p`. -/
theorem cyclotomicUnitPowerClass_torsion_eq_zeta_pow
    (hp_odd : p ≠ 2) (u : CyclotomicUnitTorsion K) :
    ∃ m : ℕ,
      cyclotomicUnitPowerClass (p := p) (N := 1) K (u : CyclotomicUnitGroup K) =
        cyclotomicUnitPowerClass (p := p) (N := 1) K
          (cyclotomicZetaUnit (p := p) K ^ m) := by
  obtain ⟨m, k, hu_eq⟩ :=
    cyclotomic_torsion_unit_eq_neg_one_pow_mul_zeta_pow
      (p := p) (K := K) hp_odd u
  refine ⟨m, ?_⟩
  rw [hu_eq, map_mul, cyclotomicUnitPowerClass_neg_one_pow_eq_one
    (p := p) (K := K) hp_odd k, one_mul]

/-- The class of `zeta_p` in `E/E^p`. -/
noncomputable abbrev cyclotomicZetaPowerClass :
    CyclotomicUnitPowerQuotient (p := p) (N := 1) K :=
  cyclotomicUnitPowerClass (p := p) (N := 1) K (cyclotomicZetaUnit (p := p) K)

/-- The image of the roots of unity in `E/E^p`. -/
abbrev cyclotomicTorsionPowerClassSubgroup :
    Subgroup (CyclotomicUnitPowerQuotient (p := p) (N := 1) K) :=
  (CyclotomicUnitTorsion K).map (cyclotomicUnitPowerClass (p := p) (N := 1) K)


end BernoulliRegular

end
