module

public import BernoulliRegular.Reflection.ResidueSymbol.Furtwaengler.StickelbergerIdealEquality.Part2.Part1

@[expose] public section

noncomputable section

open scoped NumberField

namespace BernoulliRegular

namespace Furtwaengler

universe u v w

namespace ConductorFlexibleFullTeichDworkSetup

variable {ℓ p : ℕ} [Fact (Nat.Prime ℓ)] [Fact (Nat.Prime p)]
variable {k : Type u} [Field k] [Fintype k] [Algebra (ZMod ℓ) k]
variable {K : Type v} [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]
variable {R' : Type w} [Field R'] [NumberField R'] [Algebra K R'] [IsScalarTower ℚ K R']
variable [IsScalarTower ℤ (𝓞 K) (𝓞 R')]

variable (S : ConductorFlexibleFullTeichDworkSetup ℓ p k K R')

/-- Flexible coverage predicate: a generator of the Stickelberger ideal at the
flexible descent prime. -/
def StickelbergerOrbitCoverage : Prop :=
  ∃ γ : 𝓞 K, γ ≠ 0 ∧
    Ideal.span ({γ} : Set (𝓞 K)) =
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible constructor for `StickelbergerIdealEquality` from coverage. -/
theorem stickelbergerIdealEquality_of_orbitCoverage
    (h_cov : S.StickelbergerOrbitCoverage) :
    StickelbergerIdealEquality (p := p) (K := K)
      (S.Q.under (𝓞 K)) := by
  simpa [StickelbergerIdealEquality, StickelbergerOrbitCoverage,
    ConductorFlexibleConcreteStickelbergerSetup.descentPrime] using h_cov

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible normalized-factor formula for `stickelbergerIdeal`. -/
theorem normalizedFactors_stickelbergerIdeal_descentPrime_eq :
    UniqueFactorizationMonoid.normalizedFactors
        (stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime) =
      ∑ a : CyclotomicUnitDelta p,
        ((a : ZMod p).val) •
          ({cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹
              S.concrete.descentPrime}
            : Multiset (Ideal (𝓞 K))) := by
  classical
  unfold stickelbergerIdeal
  exact S.normalizedFactors_stickelbergerIdeal_finset_eq Finset.univ

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible repeated Stickelberger multiplicity at an actual prime ideal.

This is the non-split replacement for the orbit-faithful per-index
multiplicity predicate: if several indices give the same conjugate prime, all
their `a.val` contributions are counted. -/
def StickelbergerRepeatedMultiplicity (Q : Ideal (𝓞 K)) : ℕ :=
  ∑ a : CyclotomicUnitDelta p,
    if Q = cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹ S.concrete.descentPrime then
      (a : ZMod p).val
    else
      0

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Repeated multiplicity at `σ_a⁻¹ P` as the explicit Frobenius-coset
weight.

This is the arithmetic-facing form of the non-split multiplicity: every index
`b` whose conjugate prime collapses to `σ_a⁻¹ P` contributes `b.val`, and
the collapse condition is exactly membership of `a * b⁻¹` in the subgroup
generated by the Frobenius class `ℓ mod p`. -/
theorem StickelbergerRepeatedMultiplicity_conjugate_eq_frobeniusCosetSum
    (hℓp : ℓ.Coprime p) (a : CyclotomicUnitDelta p) :
    S.StickelbergerRepeatedMultiplicity
        (cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹
          S.concrete.descentPrime) =
      ∑ b : CyclotomicUnitDelta p,
        if a * b⁻¹ ∈ Subgroup.zpowers (ZMod.unitOfCoprime ℓ hℓp) then
          (b : ZMod p).val
        else
          0 := by
  classical
  haveI : S.concrete.descentPrime.IsPrime := S.concrete.descentPrime_isPrime
  haveI : S.concrete.descentPrime.IsMaximal :=
    Ideal.IsPrime.isMaximal inferInstance S.concrete.descentPrime_ne_bot
  have h_under :
      S.concrete.descentPrime.under ℤ = Ideal.span ({(ℓ : ℤ)} : Set ℤ) :=
    CyclotomicLocalSetup.under_eq_span_of_natCast_mem
      (ℓ₀ := ℓ) (K₀ := K)
      S.concrete.descentPrime S.concrete.descentPrime_contains_ell
  letI : S.concrete.descentPrime.LiesOver (Ideal.span ({(ℓ : ℤ)} : Set ℤ)) :=
    ⟨h_under.symm⟩
  unfold StickelbergerRepeatedMultiplicity
  refine Finset.sum_congr rfl ?_
  intro b _hb
  by_cases h :
      cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹ S.concrete.descentPrime =
        cyclotomicGaloisConjugate (p := p) (K := K) b⁻¹ S.concrete.descentPrime
  · have hmem :
        a * b⁻¹ ∈ Subgroup.zpowers (ZMod.unitOfCoprime ℓ hℓp) :=
      (cyclotomicGaloisConjugate_inv_eq_inv_iff_mul_mem_frobenius_zpowers
        (p := p) (K := K) S.concrete.descentPrime hℓp a b).mp h.symm
    simp [h, hmem]
  · have hnot :
        a * b⁻¹ ∉ Subgroup.zpowers (ZMod.unitOfCoprime ℓ hℓp) := fun hmem =>
      h
        ((cyclotomicGaloisConjugate_inv_eq_inv_iff_mul_mem_frobenius_zpowers
          (p := p) (K := K) S.concrete.descentPrime hℓp a b).mpr hmem).symm
    simp [h, hnot]

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible count form of the repeated-factor Stickelberger formula. -/
theorem normalizedFactors_stickelbergerIdeal_count_eq_repeatedMultiplicity
    (Q : Ideal (𝓞 K)) :
    (UniqueFactorizationMonoid.normalizedFactors
        (stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime)).count Q =
      S.StickelbergerRepeatedMultiplicity Q := by
  classical
  rw [S.normalizedFactors_stickelbergerIdeal_descentPrime_eq]
  unfold StickelbergerRepeatedMultiplicity
  rw [Multiset.count_sum']
  refine Finset.sum_congr rfl ?_
  intro a _ha
  rw [Multiset.count_nsmul, Multiset.count_singleton]
  by_cases hQ :
      Q = cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹ S.concrete.descentPrime
  · simp [hQ]
  · simp [hQ]

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible repeated exact exponent certificate for a specific element.

The certificate is indexed by actual prime ideals, not by Galois indices, so
coincident conjugates are handled by `StickelbergerRepeatedMultiplicity`. -/
def StickelbergerRepeatedExactExponents (γ : 𝓞 K) : Prop :=
  ∀ Q : Ideal (𝓞 K),
    emultiplicity Q (Ideal.span ({γ} : Set (𝓞 K))) =
      (S.StickelbergerRepeatedMultiplicity Q : ℕ∞)

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible repeated exact exponents imply the Stickelberger span equality.

This theorem does not use splitness, orbit faithfulness, or a deduplicated
orbit.  All repeated conjugate factors have already been collected in the
actual-prime count certificate. -/
theorem span_eq_stickelbergerIdeal_of_repeatedExactExponents
    {γ : 𝓞 K} (hγ_ne : γ ≠ 0)
    (h_exp : S.StickelbergerRepeatedExactExponents γ) :
    Ideal.span ({γ} : Set (𝓞 K)) =
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime := by
  classical
  haveI := S.concrete.descentPrime_isPrime
  have hspan_ne : Ideal.span ({γ} : Set (𝓞 K)) ≠ ⊥ := by
    rwa [Ne, Ideal.span_singleton_eq_bot]
  have hstick_ne :
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime ≠ ⊥ :=
    stickelbergerIdeal_ne_bot S.concrete.descentPrime_ne_bot
  have h_dvd_left :
      Ideal.span ({γ} : Set (𝓞 K)) ∣
        stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime := by
    rw [UniqueFactorizationMonoid.dvd_iff_normalizedFactors_le_normalizedFactors
      hspan_ne hstick_ne]
    rw [Multiset.le_iff_count]
    intro Q
    by_cases hQ :
        Q ∈ UniqueFactorizationMonoid.normalizedFactors
          (Ideal.span ({γ} : Set (𝓞 K)))
    · have hQ_prime := UniqueFactorizationMonoid.prime_of_normalized_factor Q hQ
      have hQ_irred := hQ_prime.irreducible
      have hcount_span :
          emultiplicity Q (Ideal.span ({γ} : Set (𝓞 K))) =
            ((UniqueFactorizationMonoid.normalizedFactors
                (Ideal.span ({γ} : Set (𝓞 K)))).count
              (normalize Q) : ℕ∞) :=
        UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors
          hQ_irred hspan_ne
      have hnorm : normalize Q = Q := by rw [normalize_eq]
      rw [hnorm] at hcount_span
      have hcount_stick :=
        S.normalizedFactors_stickelbergerIdeal_count_eq_repeatedMultiplicity Q
      have h_exp_Q := h_exp Q
      rw [← hcount_stick] at h_exp_Q
      have h_eq_count :
          ((UniqueFactorizationMonoid.normalizedFactors
              (Ideal.span ({γ} : Set (𝓞 K)))).count Q : ℕ∞) =
            (((UniqueFactorizationMonoid.normalizedFactors
                (stickelbergerIdeal (p := p) (K := K)
                  S.concrete.descentPrime)).count Q) : ℕ∞) := by
        rw [← hcount_span]
        exact h_exp_Q
      exact_mod_cast h_eq_count.le
    · rw [Multiset.count_eq_zero.mpr hQ]
      exact Nat.zero_le _
  have h_dvd_right :
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime ∣
        Ideal.span ({γ} : Set (𝓞 K)) := by
    rw [UniqueFactorizationMonoid.dvd_iff_normalizedFactors_le_normalizedFactors
      hstick_ne hspan_ne]
    rw [Multiset.le_iff_count]
    intro Q
    by_cases hQ :
        Q ∈ UniqueFactorizationMonoid.normalizedFactors
          (stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime)
    · have hQ_prime := UniqueFactorizationMonoid.prime_of_normalized_factor Q hQ
      have hQ_irred := hQ_prime.irreducible
      have hcount_span :
          emultiplicity Q (Ideal.span ({γ} : Set (𝓞 K))) =
            ((UniqueFactorizationMonoid.normalizedFactors
                (Ideal.span ({γ} : Set (𝓞 K)))).count
              (normalize Q) : ℕ∞) :=
        UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors
          hQ_irred hspan_ne
      have hnorm : normalize Q = Q := by rw [normalize_eq]
      rw [hnorm] at hcount_span
      have hcount_stick :=
        S.normalizedFactors_stickelbergerIdeal_count_eq_repeatedMultiplicity Q
      have h_exp_Q := h_exp Q
      rw [← hcount_stick] at h_exp_Q
      have h_eq_count :
          (((UniqueFactorizationMonoid.normalizedFactors
              (stickelbergerIdeal (p := p) (K := K)
                S.concrete.descentPrime)).count Q) : ℕ∞) =
            ((UniqueFactorizationMonoid.normalizedFactors
                (Ideal.span ({γ} : Set (𝓞 K)))).count Q : ℕ∞) := by
        rw [← hcount_span]
        exact h_exp_Q.symm
      exact_mod_cast h_eq_count.le
    · rw [Multiset.count_eq_zero.mpr hQ]
      exact Nat.zero_le _
  exact associated_iff_eq.mp (associated_of_dvd_dvd h_dvd_left h_dvd_right)

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible repeated exact exponent certificate restricted to the cyclotomic
orbit of the descent prime.

Together with `StickelbergerSupportInOrbit`, this is enough to compare all
normalized-factor counts. -/
def StickelbergerRepeatedExactExponentsOnOrbit (γ : 𝓞 K) : Prop :=
  ∀ a : CyclotomicUnitDelta p,
    emultiplicity
        (cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹ S.concrete.descentPrime)
        (Ideal.span ({γ} : Set (𝓞 K))) =
      (S.StickelbergerRepeatedMultiplicity
        (cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹ S.concrete.descentPrime) :
          ℕ∞)

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible API: to prove the orbit-indexed repeated exact exponent
certificate, it suffices to prove the selected-prime valuation of every
cyclotomic conjugate of the element. -/
theorem stickelbergerRepeatedExactExponentsOnOrbit_of_conjugate_descentPrime_emultiplicity
    {γ : 𝓞 K}
    (h :
      ∀ a : CyclotomicUnitDelta p,
        emultiplicity S.concrete.descentPrime
            (Ideal.span
              ({cyclotomicRingOfIntegersEquiv (p := p) K a γ} : Set (𝓞 K))) =
          (S.StickelbergerRepeatedMultiplicity
            (cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹
              S.concrete.descentPrime) : ℕ∞)) :
    S.StickelbergerRepeatedExactExponentsOnOrbit γ := by
  intro a
  rw [emultiplicity_conjugatePrime_span_eq_descentPrime_conjugateElement]
  exact h a

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible repeated exact exponents on the orbit, plus support containment,
imply the Stickelberger span equality.

This is the arbitrary-degree analogue of the old atomic split discharge, but
the multiplicity target is the repeated actual-prime count rather than the
deduplicated per-index count. -/
theorem span_eq_stickelbergerIdeal_of_supportInOrbit_of_repeatedExactOnOrbit
    {γ : 𝓞 K} (hγ_ne : γ ≠ 0)
    (h_sup : S.StickelbergerSupportInOrbit γ)
    (h_exp : S.StickelbergerRepeatedExactExponentsOnOrbit γ) :
    Ideal.span ({γ} : Set (𝓞 K)) =
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime := by
  classical
  haveI := S.concrete.descentPrime_isPrime
  have hspan_ne : Ideal.span ({γ} : Set (𝓞 K)) ≠ ⊥ := by
    rwa [Ne, Ideal.span_singleton_eq_bot]
  have hstick_ne :
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime ≠ ⊥ :=
    stickelbergerIdeal_ne_bot S.concrete.descentPrime_ne_bot
  have h_dvd_left :
      Ideal.span ({γ} : Set (𝓞 K)) ∣
        stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime := by
    rw [UniqueFactorizationMonoid.dvd_iff_normalizedFactors_le_normalizedFactors
      hspan_ne hstick_ne]
    rw [Multiset.le_iff_count]
    intro Q
    by_cases hQ :
        Q ∈ UniqueFactorizationMonoid.normalizedFactors
          (Ideal.span ({γ} : Set (𝓞 K)))
    · have hQ_orbit := h_sup Q hQ
      obtain ⟨c, hc_eq⟩ :=
        (mem_cyclotomicConjugates_iff (p := p) (K := K) _ Q).mp hQ_orbit
      have hQ_prime := UniqueFactorizationMonoid.prime_of_normalized_factor Q hQ
      have hQ_irred := hQ_prime.irreducible
      have hcount_span :
          emultiplicity Q (Ideal.span ({γ} : Set (𝓞 K))) =
            ((UniqueFactorizationMonoid.normalizedFactors
                (Ideal.span ({γ} : Set (𝓞 K)))).count
              (normalize Q) : ℕ∞) :=
        UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors
          hQ_irred hspan_ne
      have hnorm : normalize Q = Q := by rw [normalize_eq]
      rw [hnorm] at hcount_span
      have h_exp_Q := h_exp c⁻¹
      rw [inv_inv, hc_eq] at h_exp_Q
      have hcount_stick :=
        S.normalizedFactors_stickelbergerIdeal_count_eq_repeatedMultiplicity Q
      rw [← hcount_stick] at h_exp_Q
      have h_eq_count :
          ((UniqueFactorizationMonoid.normalizedFactors
              (Ideal.span ({γ} : Set (𝓞 K)))).count Q : ℕ∞) =
            (((UniqueFactorizationMonoid.normalizedFactors
                (stickelbergerIdeal (p := p) (K := K)
                  S.concrete.descentPrime)).count Q) : ℕ∞) := by
        rw [← hcount_span]
        exact h_exp_Q
      exact_mod_cast h_eq_count.le
    · rw [Multiset.count_eq_zero.mpr hQ]
      exact Nat.zero_le _
  have h_dvd_right :
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime ∣
        Ideal.span ({γ} : Set (𝓞 K)) := by
    rw [UniqueFactorizationMonoid.dvd_iff_normalizedFactors_le_normalizedFactors
      hstick_ne hspan_ne]
    rw [Multiset.le_iff_count]
    intro Q
    by_cases hQ :
        Q ∈ UniqueFactorizationMonoid.normalizedFactors
          (stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime)
    · have hQ_orbit :
          Q ∈ cyclotomicConjugates (p := p) (K := K) S.concrete.descentPrime :=
        normalizedFactors_stickelbergerIdeal_subset (p := p) (K := K)
          S.concrete.descentPrime_ne_bot hQ
      obtain ⟨c, hc_eq⟩ :=
        (mem_cyclotomicConjugates_iff (p := p) (K := K) _ Q).mp hQ_orbit
      have hQ_prime := UniqueFactorizationMonoid.prime_of_normalized_factor Q hQ
      have hQ_irred := hQ_prime.irreducible
      have hcount_span :
          emultiplicity Q (Ideal.span ({γ} : Set (𝓞 K))) =
            ((UniqueFactorizationMonoid.normalizedFactors
                (Ideal.span ({γ} : Set (𝓞 K)))).count
              (normalize Q) : ℕ∞) :=
        UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors
          hQ_irred hspan_ne
      have hnorm : normalize Q = Q := by rw [normalize_eq]
      rw [hnorm] at hcount_span
      have h_exp_Q := h_exp c⁻¹
      rw [inv_inv, hc_eq] at h_exp_Q
      have hcount_stick :=
        S.normalizedFactors_stickelbergerIdeal_count_eq_repeatedMultiplicity Q
      rw [← hcount_stick] at h_exp_Q
      have h_eq_count :
          (((UniqueFactorizationMonoid.normalizedFactors
              (stickelbergerIdeal (p := p) (K := K)
                S.concrete.descentPrime)).count Q) : ℕ∞) =
            ((UniqueFactorizationMonoid.normalizedFactors
                (Ideal.span ({γ} : Set (𝓞 K)))).count Q : ℕ∞) := by
        rw [← hcount_span]
        exact h_exp_Q.symm
      exact_mod_cast h_eq_count.le
    · rw [Multiset.count_eq_zero.mpr hQ]
      exact Nat.zero_le _
  exact associated_iff_eq.mp (associated_of_dvd_dvd h_dvd_left h_dvd_right)

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible multiplicity count in the Stickelberger ideal under orbit
faithfulness. -/
theorem stickelbergerIdealConjugateMultiplicity_of_orbitFaithful
    (h_faithful : S.StickelbergerOrbitFaithful) :
    S.StickelbergerIdealConjugateMultiplicity := by
  classical
  intro a
  rw [S.normalizedFactors_stickelbergerIdeal_descentPrime_eq]
  rw [Multiset.count_sum']
  rw [Finset.sum_eq_single a]
  · rw [Multiset.count_nsmul, Multiset.count_singleton_self, mul_one]
  · intro b _ hba
    rw [Multiset.count_nsmul, Multiset.count_singleton]
    have h_ne : cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹
          S.concrete.descentPrime ≠
        cyclotomicGaloisConjugate (p := p) (K := K) b⁻¹
          S.concrete.descentPrime := fun h =>
      hba <| (h_faithful h).symm
    rw [if_neg h_ne, Nat.mul_zero]
  · intro h
    exact absurd (Finset.mem_univ a) h

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible injectivity of the orbit indexing from maximum orbit cardinality. -/
theorem cyclotomicGaloisConjugate_descentPrime_injective_of_card_eq
    (h_card :
      (cyclotomicConjugates (p := p) (K := K)
        S.concrete.descentPrime).card = p - 1) :
    Function.Injective (fun a : CyclotomicUnitDelta p =>
      cyclotomicGaloisConjugate (p := p) (K := K) a
        S.concrete.descentPrime) := by
  classical
  have h_image_card :
      (Finset.univ.image (fun a : CyclotomicUnitDelta p =>
        cyclotomicGaloisConjugate (p := p) (K := K) a
          S.concrete.descentPrime)).card = p - 1 := by
    rw [show (Finset.univ.image (fun a : CyclotomicUnitDelta p =>
        cyclotomicGaloisConjugate (p := p) (K := K) a
          S.concrete.descentPrime)) =
      cyclotomicConjugates (p := p) (K := K)
        S.concrete.descentPrime from rfl]
    exact h_card
  have h_univ_card :
      (Finset.univ : Finset (CyclotomicUnitDelta p)).card = p - 1 := by
    rw [Finset.card_univ]
    exact ZMod.card_units p
  have h_card_eq :
      (Finset.univ.image (fun a : CyclotomicUnitDelta p =>
        cyclotomicGaloisConjugate (p := p) (K := K) a
          S.concrete.descentPrime)).card =
        (Finset.univ : Finset (CyclotomicUnitDelta p)).card := by
    rw [h_image_card, h_univ_card]
  have h_injOn :
      Set.InjOn
        (fun a : CyclotomicUnitDelta p =>
          cyclotomicGaloisConjugate (p := p) (K := K) a
            S.concrete.descentPrime)
        (Finset.univ : Finset (CyclotomicUnitDelta p)) :=
    Finset.card_image_iff.mp h_card_eq
  intro a b hab
  exact h_injOn (Finset.mem_univ a) (Finset.mem_univ b) hab

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible orbit faithfulness from maximum orbit cardinality. -/
theorem stickelbergerOrbitFaithful_of_card_eq
    (h_card :
      (cyclotomicConjugates (p := p) (K := K)
        S.concrete.descentPrime).card = p - 1) :
    S.StickelbergerOrbitFaithful := by
  classical
  have h_inj :=
    S.cyclotomicGaloisConjugate_descentPrime_injective_of_card_eq h_card
  have h_inv : Function.Injective (Inv.inv : CyclotomicUnitDelta p → CyclotomicUnitDelta p) :=
    inv_injective
  intro a b hab
  exact h_inv (h_inj hab)

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible orbit faithfulness from total splitting of the descent prime. -/
theorem stickelbergerOrbitFaithful_of_split
    (he : (S.concrete.descentPrime.under ℤ).ramificationIdxIn (𝓞 K) = 1)
    (hf : (S.concrete.descentPrime.under ℤ).inertiaDegIn (𝓞 K) = 1) :
    S.StickelbergerOrbitFaithful := by
  haveI := S.concrete.descentPrime_isPrime
  have h_card :
      (cyclotomicConjugates (p := p) (K := K)
        S.concrete.descentPrime).card = p - 1 :=
    cyclotomicConjugates_card_eq_p_sub_one_of_split
      (p := p) (K := K)
      (q := S.concrete.descentPrime)
      S.concrete.descentPrime_ne_bot he hf
  exact S.stickelbergerOrbitFaithful_of_card_eq h_card

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- The flexible Stickelberger ideal at the descent prime is non-bot. -/
theorem stickelbergerIdeal_descentPrime_ne_bot :
    stickelbergerIdeal (p := p) (K := K)
        S.concrete.descentPrime ≠ ⊥ :=
  haveI := S.concrete.descentPrime_isPrime
  stickelbergerIdeal_ne_bot S.concrete.descentPrime_ne_bot

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible lower bound for emultiplicity in the Stickelberger ideal. -/
theorem emultiplicity_stickelbergerIdeal_ge_aval
    (a : CyclotomicUnitDelta p) :
    ((a : ZMod p).val : ℕ∞) ≤
      emultiplicity
        (cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹
          S.concrete.descentPrime)
        (stickelbergerIdeal (p := p) (K := K)
          S.concrete.descentPrime) := by
  haveI := S.concrete.descentPrime_isPrime
  have hle :=
    stickelbergerIdeal_le_factor (p := p) (K := K)
      S.concrete.descentPrime a
  have hdvd :
      cyclotomicGaloisConjugate (p := p) (K := K) a⁻¹
            S.concrete.descentPrime ^
          ((a : ZMod p).val) ∣
        stickelbergerIdeal (p := p) (K := K)
          S.concrete.descentPrime :=
    Ideal.dvd_iff_le.mpr hle
  exact pow_dvd_iff_le_emultiplicity.mp hdvd

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible forward divisibility from exact exponents and support. -/
theorem span_dvd_stickelbergerIdeal_of_atomic
    {γ : 𝓞 K} (hγ_ne : γ ≠ 0)
    (h_exp : S.StickelbergerExactConjugateExponents γ)
    (h_sup : S.StickelbergerSupportInOrbit γ) :
    Ideal.span ({γ} : Set (𝓞 K)) ∣
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime := by
  classical
  haveI := S.concrete.descentPrime_isPrime
  have hspan_ne : Ideal.span ({γ} : Set (𝓞 K)) ≠ ⊥ := by
    rwa [Ne, Ideal.span_singleton_eq_bot]
  have hstick_ne : stickelbergerIdeal (p := p) (K := K)
      S.concrete.descentPrime ≠ ⊥ :=
    S.stickelbergerIdeal_descentPrime_ne_bot
  rw [UniqueFactorizationMonoid.dvd_iff_normalizedFactors_le_normalizedFactors
        hspan_ne hstick_ne]
  rw [Multiset.le_iff_count]
  intro b
  by_cases hb_in :
      b ∈ UniqueFactorizationMonoid.normalizedFactors
        (Ideal.span ({γ} : Set (𝓞 K)))
  · have hb_orbit := h_sup b hb_in
    obtain ⟨c, hc_eq⟩ :=
      (mem_cyclotomicConjugates_iff (p := p) (K := K) _ b).mp hb_orbit
    have hb_prime :=
      UniqueFactorizationMonoid.prime_of_normalized_factor b hb_in
    have hb_irred := hb_prime.irreducible
    have hcount_γ :
        emultiplicity b (Ideal.span ({γ} : Set (𝓞 K))) =
          ((UniqueFactorizationMonoid.normalizedFactors
              (Ideal.span ({γ} : Set (𝓞 K)))).count
            (normalize b) : ℕ∞) :=
      UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hb_irred hspan_ne
    have hnorm : normalize b = b := by rw [normalize_eq]
    rw [hnorm] at hcount_γ
    have h_emult_γ := h_exp c⁻¹
    rw [inv_inv, hc_eq] at h_emult_γ
    rw [h_emult_γ] at hcount_γ
    have hcount_γ_nat :
        (UniqueFactorizationMonoid.normalizedFactors
            (Ideal.span ({γ} : Set (𝓞 K)))).count b =
          ((c⁻¹ : CyclotomicUnitDelta p) : ZMod p).val := by
      have := hcount_γ.symm
      exact_mod_cast this
    rw [hcount_γ_nat]
    have h_stick_lb := S.emultiplicity_stickelbergerIdeal_ge_aval c⁻¹
    rw [inv_inv, hc_eq] at h_stick_lb
    have hcount_stick :
        emultiplicity b
            (stickelbergerIdeal (p := p) (K := K)
              S.concrete.descentPrime) =
          ((UniqueFactorizationMonoid.normalizedFactors
              (stickelbergerIdeal (p := p) (K := K)
                S.concrete.descentPrime)).count
            (normalize b) : ℕ∞) :=
      UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hb_irred hstick_ne
    rw [hnorm] at hcount_stick
    rw [hcount_stick] at h_stick_lb
    exact_mod_cast h_stick_lb
  · rw [Multiset.count_eq_zero.mpr hb_in]
    exact Nat.zero_le _

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible reverse divisibility from exact exponents and structural
Stickelberger multiplicities. -/
theorem stickelbergerIdeal_dvd_span_of_exact_atomic
    {γ : 𝓞 K} (hγ_ne : γ ≠ 0)
    (h_exp : S.StickelbergerExactConjugateExponents γ)
    (h_stickMul : S.StickelbergerIdealConjugateMultiplicity) :
    stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime ∣
      Ideal.span ({γ} : Set (𝓞 K)) := by
  classical
  haveI := S.concrete.descentPrime_isPrime
  have hspan_ne : Ideal.span ({γ} : Set (𝓞 K)) ≠ ⊥ := by
    rwa [Ne, Ideal.span_singleton_eq_bot]
  have hstick_ne : stickelbergerIdeal (p := p) (K := K)
      S.concrete.descentPrime ≠ ⊥ :=
    S.stickelbergerIdeal_descentPrime_ne_bot
  rw [UniqueFactorizationMonoid.dvd_iff_normalizedFactors_le_normalizedFactors
        hstick_ne hspan_ne]
  rw [Multiset.le_iff_count]
  intro b
  by_cases hb_in :
      b ∈ UniqueFactorizationMonoid.normalizedFactors
        (stickelbergerIdeal (p := p) (K := K)
          S.concrete.descentPrime)
  · have hb_orbit :
        b ∈ cyclotomicConjugates (p := p) (K := K)
          S.concrete.descentPrime :=
      normalizedFactors_stickelbergerIdeal_subset (p := p) (K := K)
        S.concrete.descentPrime_ne_bot hb_in
    obtain ⟨c, hc_eq⟩ :=
      (mem_cyclotomicConjugates_iff (p := p) (K := K) _ b).mp hb_orbit
    have hb_prime :=
      UniqueFactorizationMonoid.prime_of_normalized_factor b hb_in
    have hb_irred := hb_prime.irreducible
    have h_stick_count := h_stickMul c⁻¹
    rw [inv_inv, hc_eq] at h_stick_count
    rw [h_stick_count]
    have h_emult_γ := h_exp c⁻¹
    rw [inv_inv, hc_eq] at h_emult_γ
    have hcount_γ :
        emultiplicity b (Ideal.span ({γ} : Set (𝓞 K))) =
          ((UniqueFactorizationMonoid.normalizedFactors
              (Ideal.span ({γ} : Set (𝓞 K)))).count
            (normalize b) : ℕ∞) :=
      UniqueFactorizationMonoid.emultiplicity_eq_count_normalizedFactors hb_irred hspan_ne
    have hnorm : normalize b = b := by rw [normalize_eq]
    rw [hnorm] at hcount_γ
    rw [h_emult_γ] at hcount_γ
    have hcount_γ_nat :
        (UniqueFactorizationMonoid.normalizedFactors
            (Ideal.span ({γ} : Set (𝓞 K)))).count b =
          ((c⁻¹ : CyclotomicUnitDelta p) : ZMod p).val := by
      have := hcount_γ.symm
      exact_mod_cast this
    rw [hcount_γ_nat]
  · rw [Multiset.count_eq_zero.mpr hb_in]
    exact Nat.zero_le _

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible direct span equality from atomic predicates. -/
theorem span_eq_stickelbergerIdeal_of_atomic
    {γ : 𝓞 K} (hγ_ne : γ ≠ 0)
    (h_exp : S.StickelbergerExactConjugateExponents γ)
    (h_sup : S.StickelbergerSupportInOrbit γ)
    (h_stickMul : S.StickelbergerIdealConjugateMultiplicity) :
    Ideal.span ({γ} : Set (𝓞 K)) =
      stickelbergerIdeal (p := p) (K := K) S.concrete.descentPrime := by
  have h_dvd1 := S.span_dvd_stickelbergerIdeal_of_atomic hγ_ne h_exp h_sup
  have h_dvd2 := S.stickelbergerIdeal_dvd_span_of_exact_atomic hγ_ne h_exp h_stickMul
  exact associated_iff_eq.mp (associated_of_dvd_dvd h_dvd1 h_dvd2)

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible coverage from atomic predicates and structural multiplicities. -/
theorem stickelbergerOrbitCoverage_of_atomic_with_stickMul
    {γ : 𝓞 K} (hγ_ne : γ ≠ 0)
    (h_exp : S.StickelbergerExactConjugateExponents γ)
    (h_sup : S.StickelbergerSupportInOrbit γ)
    (h_stickMul : S.StickelbergerIdealConjugateMultiplicity) :
    S.StickelbergerOrbitCoverage :=
  ⟨γ, hγ_ne, S.span_eq_stickelbergerIdeal_of_atomic hγ_ne h_exp h_sup h_stickMul⟩

omit [IsScalarTower ℤ (𝓞 K) (𝓞 R')] in
/-- Flexible `StickelbergerIdealEquality` from atomic predicates and structural
multiplicities. -/
theorem stickelbergerIdealEquality_of_atomic_with_stickMul
    {γ : 𝓞 K} (hγ_ne : γ ≠ 0)
    (h_exp : S.StickelbergerExactConjugateExponents γ)
    (h_sup : S.StickelbergerSupportInOrbit γ)
    (h_stickMul : S.StickelbergerIdealConjugateMultiplicity) :
    StickelbergerIdealEquality (p := p) (K := K)
      (S.Q.under (𝓞 K)) :=
  S.stickelbergerIdealEquality_of_orbitCoverage
    (S.stickelbergerOrbitCoverage_of_atomic_with_stickMul hγ_ne h_exp h_sup h_stickMul)


end ConductorFlexibleFullTeichDworkSetup

end Furtwaengler

end BernoulliRegular

end
