module

import Mathlib.RingTheory.Localization.AtPrime.Basic
public import BernoulliRegular.TotallyRealSubfield.ZetaPrime

/-!
# Local cyclotomic setup at `lambda`

This file packages the basic local objects used in the reflection argument by
localizing `𝓞 K` at the distinguished prime `zetaPrime p K` generated by
`ζ_p - 1`.

At this stage we only need the local ring, its maximal ideal, the unit group,
and the principal-unit filtration. Those are the REF-09 inputs for the later
local calculations.
-/

@[expose] public section

noncomputable section

open scoped NumberField

namespace BernoulliRegular

namespace Ideal

section OneUnits

variable {R : Type*} [CommRing R]

/-- The subgroup of units congruent to `1` modulo `I`. -/
def oneUnitsSubgroup (I : Ideal R) : Subgroup Rˣ where
  carrier := {u | (u : R) - 1 ∈ I}
  one_mem' := by
    simp
  mul_mem' {u v} hu hv := by
    simpa using I.mul_sub_mul_mem hu hv
  inv_mem' {u} hu := by
    have hmul : ((u : R) * (((u⁻¹ : Rˣ) : R) - 1)) ∈ I := by
      simpa [sub_eq_add_neg, mul_add, add_comm, add_left_comm, add_assoc] using I.neg_mem hu
    exact
      (Ideal.unit_mul_mem_iff_mem (I := I) (x := ((((u⁻¹ : Rˣ) : R) - 1))) (y := (u : R))
        u.isUnit).mp hmul

@[simp]
theorem mem_oneUnitsSubgroup {R : Type*} [CommRing R] {I : Ideal R} {u : Rˣ} :
  u ∈ Ideal.oneUnitsSubgroup I ↔ (u : R) - 1 ∈ I :=
  Iff.rfl

end OneUnits

end Ideal

namespace Reflection
namespace Local

section CyclotomicSetup

variable (p : ℕ) [Fact p.Prime]
  (K : Type*) [Field K] [NumberField K] [IsCyclotomicExtension {p} ℚ K]

/-- The distinguished prime `lambda = (ζ_p - 1)` above `p` in `𝓞 K`. -/
abbrev cyclotomicLambda : Ideal (𝓞 K) := zetaPrime p K

/-- The localization of `𝓞 K` at the distinguished prime `lambda = (ζ_p - 1)`. -/
abbrev localCyclotomicRing := Localization.AtPrime (cyclotomicLambda p K)


/-- The maximal ideal in the localized ring, i.e. the local avatar of `lambda`. -/
abbrev localCyclotomicMaximalIdeal : Ideal (localCyclotomicRing p K) :=
  IsLocalRing.maximalIdeal (localCyclotomicRing p K)

/-- The local unit group `U = O_Fˣ` at `lambda`. -/
abbrev localCyclotomicUnitGroup := (localCyclotomicRing p K)ˣ

/-- The principal-unit filtration `U_n = 1 + lambda^n O_F`. -/
def principalUnitSubgroup (n : ℕ) : Subgroup (localCyclotomicUnitGroup p K) :=
  Ideal.oneUnitsSubgroup ((localCyclotomicMaximalIdeal p K) ^ n)

theorem localCyclotomicMaximalIdeal_eq_map :
  Ideal.map (algebraMap (𝓞 K) (localCyclotomicRing p K)) (cyclotomicLambda p K) =
      localCyclotomicMaximalIdeal p K := by
  simpa [localCyclotomicMaximalIdeal, localCyclotomicRing] using
  (Localization.AtPrime.map_eq_maximalIdeal (R := 𝓞 K) (I := cyclotomicLambda p K))

theorem localCyclotomicMaximalIdeal_comap :
    Ideal.comap (algebraMap (𝓞 K) (localCyclotomicRing p K))
    (localCyclotomicMaximalIdeal p K) = cyclotomicLambda p K := by
  simpa [localCyclotomicMaximalIdeal, localCyclotomicRing] using
  (Localization.AtPrime.comap_maximalIdeal (R := 𝓞 K) (I := cyclotomicLambda p K))

@[simp]
theorem mem_principalUnitSubgroup_iff {n : ℕ} {u : localCyclotomicUnitGroup p K} :
    u ∈ principalUnitSubgroup p K n ↔
      (u : localCyclotomicRing p K) - 1 ∈ (localCyclotomicMaximalIdeal p K) ^ n :=
  by
    change u ∈ Ideal.oneUnitsSubgroup ((localCyclotomicMaximalIdeal p K) ^ n) ↔
      (u : localCyclotomicRing p K) - 1 ∈ (localCyclotomicMaximalIdeal p K) ^ n
    exact Ideal.mem_oneUnitsSubgroup

end CyclotomicSetup

end Local
end Reflection

end BernoulliRegular
